---
title: "integration of wound healing"
author: "Zhuang Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 6, warning=FALSE, message=FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(patchwork)
library(harmony)
```


# 1. Prepare wound data
```{r}
outname="Lymphoid"
```

# 2. Integrate the human and VU, DFU chronic wound data
```{r eval=TRUE}
# vu data and acute wound data
vu_seu <- readRDS("../subCellTypeInte_acute_vu/allWound_acute_vu_integrated_Lym.rds")
DefaultAssay(vu_seu) = "RNA"
vu_seu <- DietSeurat(vu_seu, assays = "RNA")

# DFU data
hs_seu <- readRDS("../subCellTypeInte_acute_dfu/step8_DFU_Wound_Lymphoid.rds")
hs_seu
hs_seu <- subset(hs_seu, subset= Project == "DFU")
DefaultAssay(hs_seu) = "RNA"
hs_seu <- DietSeurat(hs_seu, assays = "RNA")

# check the overlapped genes and keep the overlapped genes
overgene <- intersect(rownames(vu_seu), rownames(hs_seu))
length(overgene)

vu_seu <- vu_seu[overgene, ]
hs_seu <- hs_seu[overgene, ]

# integrate based on orig.ident names
#vu_seu$Project="VU"
#vu_seu$CellType=vu_seu$CellType
hs_seu$orig.ident=hs_seu$Donor1
#hs_seu$Project="DFU"
hs_seu$CellType=hs_seu$CellType
```

# 3. sctransform normalization
```{r eval=TRUE}
all_seu <- merge(vu_seu, y = c(hs_seu),
                project = "wounds")

rm(vu_seu);rm(hs_seu);gc()

alldata = SplitObject(all_seu, split.by = "orig.ident")
alldata <- lapply(X = alldata, FUN = function(x) {
  x <- NormalizeData(x)
  x <- CellCycleScoring(x, s.features = cc.genes.updated.2019$s.genes, g2m.features = cc.genes.updated.2019$g2m.genes, set.ident = F)
})
for (i in seq_along(alldata)) {
  alldata[[i]]$CC.Difference <- alldata[[i]]$S.Score - alldata[[i]]$G2M.Score
}

rm(all_seu)
alldata <- lapply(X = alldata, FUN = SCTransform, method = "glmGamPoi", vars.to.regress = c("CC.Difference"))
```


# 4. Run harmony Clustering
```{r eval=TRUE}
# Run harmony using SCTransform
options(future.globals.maxSize = 1000000 * 1024^2) 
features <- SelectIntegrationFeatures(object.list = alldata, nfeatures = 4000)

alldata <- PrepSCTIntegration(object.list = alldata, anchor.features = features)
inteData <- merge(alldata[[1]], y = c(alldata[2:length(alldata)]), merge.data = TRUE)
VariableFeatures(inteData) <- features
rm(alldata);gc()

inteData <- RunPCA(inteData, npcs = 50, assay = "SCT")
ElbowPlot(inteData, ndims = 50)
table(inteData$orig.ident)
# RunHarmony parameter: assay.use only for Seurat V3
inteData <- RunHarmony(inteData, #assay.use = "SCT", reduction = "pca", 
		       dims.use = 1:30, 
                       group.by.vars = "orig.ident", plot_convergence = TRUE)

inteData <- RunUMAP(inteData, dims = 1:30, assay = "SCT", reduction = "harmony", n.neighbors = 40)
DimPlot(inteData, group.by = "orig.ident") + NoAxes()

inteData = FindNeighbors(inteData, dims = 1:30, reduction = "harmony", k.param = 40)
inteData = FindClusters(inteData, resolution = 0.3)
inteData = FindClusters(inteData, resolution = 1)
inteData = FindClusters(inteData, resolution = 1.5)
inteData = FindClusters(inteData, resolution = 2)
inteData = FindClusters(inteData, resolution = 1.2)
inteData = FindClusters(inteData, resolution = 0.5)
inteData = FindClusters(inteData, resolution = 0.8)

inteData$Condition <- factor(inteData$Condition, levels = c("Skin", "Wound1", "Wound7", "Wound30","H", "DFU_NH", "DFU_H", "NS", "VU"))

DimPlot(inteData, group.by = "SCT_snn_res.1", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.5", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.8", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.8", label = T, split.by = "Condition", raster=FALSE)  
DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)
```


# 5. CellType plotting
```{r fig.width=12, fig.height=8}
DimPlot(inteData, group.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 
DimPlot(inteData, group.by = "Project", split.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 


DimPlot(inteData, group.by = "CellType", label = T, split.by = "Project", raster=FALSE) + ggtitle("")
DimPlot(inteData, group.by = "CellType", label = T, split.by = "Condition", ncol = 4, raster=FALSE) + ggtitle("") + NoLegend()
```


# 6. Data exporting
```{r}
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inte", outname, ".rds"))

# export the reduced results for quickly plotting
inteData@reductions$pca@assay.used <- "RNA"
inteData@reductions$harmony@assay.used <- "RNA"
inteData@reductions$umap@assay.used <- "RNA"

inteData <- DietSeurat(inteData, assays = "RNA", dimreducs = c("umap"))
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inte", outname, "_redu.rds"))
```


# manuscript plotting
```{r eval=FALSE}
#If you are using Seurat V5 but do not want to use the V5 Assay, 
#you can set the option to "v3"
options(Seurat.object.assay.version = 'v3')

library(scCustomize)
library(Seurat)
library(SeuratObject)
library(tidyverse)
library(patchwork)
library(ggplot2)

inteData <- readRDS("allacuteWound_DFU_VU_inteLymphoid.rds")
inteData
DimPlot(inteData, group.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 
DimPlot(inteData, group.by = "Project", split.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE)

DimPlot(inteData, group.by = "CellType", label = T, split.by = "Project", raster=FALSE) + ggtitle("") + NoLegend()
DimPlot(inteData, group.by = "CellType", label = T, split.by = "Condition", ncol = 4, raster=FALSE) + ggtitle("") + NoLegend()
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 raster=F, #pt.size = 1, 
                 label.size = 4,
                 num_columns = 3) & NoLegend()

DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)

FeaturePlot_scCustom(inteData,  features = c("CCR6"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("PTGER4"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("ANKRD28"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("FXYD2"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("TRGC2"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KLRC2"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KLRC3"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("GZMK"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("HSPA1B"), split.by = "Condition", 
                     num_columns = 3)
table(inteData$Condition, inteData$SCT_snn_res.1.2)
table(inteData$CellType, inteData$SCT_snn_res.1.2)

DefaultAssay(inteData) <- "SCT"
inteData = FindClusters(inteData, resolution = 1.5)
inteData = FindClusters(inteData, resolution = 1.8)
inteData = FindClusters(inteData, resolution = 3)
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.1.5", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.3", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

# remove some inconsistent clusters or doublets through checking some markers below
inteData$fil <- ifelse(inteData$SCT_snn_res.3 %in% c(26), "keep", "no")
inteData <- subset(inteData, subset = fil == "no")
inteData@meta.data <- droplevels(inteData@meta.data)

table(inteData$CellType, inteData$SCT_snn_res.1.2)
table(inteData$Condition, inteData$SCT_snn_res.1.5)

### re-run the UMAP
#inteData <- RunUMAP(inteData, dims = 1:30, assay = "SCT", reduction = "harmony", n.neighbors = 40, n.epochs = 500)

DimPlot(inteData, group.by = "SCT_snn_res.1.5", label = T)
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.1.5", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.1.5", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

# Check the marker genes
DefaultAssay(inteData) <- "RNA"
FeaturePlot_scCustom(inteData,  features = c("TNFRSF9"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("GNLY"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("XCL2"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot(inteData,  features = c("NR4A1"), cols = c("grey90", "red"))

FeaturePlot_scCustom(inteData,  features = c("GZMK"))

Idents(inteData) <- inteData$SCT_snn_res.1.5
Cluster_Highlight_Plot(seurat_object = inteData, 
                       cluster_name = c("8","14","12","11"), #12,20,25,27,29
                       highlight_color = c("navy","forestgreen", "red", "pink"),
                       background_color = "lightgray")
table(inteData$CellType, inteData$SCT_snn_res.1.5)
table(inteData$SCT_snn_res.0.8, inteData$SCT_snn_res.1.8)

Idents(inteData) <- inteData$CellType
Cluster_Highlight_Plot(seurat_object = inteData, 
                       cluster_name = c("Ttol","Th","ILCs", "Tc"), 
                       highlight_color = c("red", "navy","forestgreen", "pink"),
                       background_color = "lightgray")

# re-annotate the cell clusters based on 1.5
anno.cl <- list()
anno.cl$Treg = c(4,7) 
anno.cl$Th = c(0,3,6) 
anno.cl$ILCs = c(9) 
anno.cl$Tc = c(14) 
anno.cl$ILC1_NK = c(5,16) 
anno.cl$NK = c(12) 
anno.cl$Ttol = c(1,2,8,10,13) 
anno.cl$Plasma = c(11) 
anno.cl$Bcell = c(15)

trans = rep(names(anno.cl), times = unlist(lapply(anno.cl, length)))
names(trans) = unlist(anno.cl)
mt <- inteData@meta.data
mt$newCellType <- trans[as.character(mt$SCT_snn_res.1.5)]
inteData$newCellType <- mt$newCellType
table(inteData$newCellType)
DimPlot(inteData, group.by = "newCellType", label = T) + NoAxes()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T, label.size = 3,
                 num_columns = 3) & NoLegend()

table(inteData$newCellType, inteData$Condition)
table(inteData$CellType, inteData$SCT_snn_res.3)

Idents(inteData) <- inteData$newCellType
Cluster_Highlight_Plot(seurat_object = inteData, 
                       cluster_name = c("ILCs", "Tc", "ILC1_NK", "NK"), 
                       highlight_color = c("red", "navy","forestgreen", "pink"),
                       background_color = "lightgray")

fac_levs <- c("Treg", "Th", "ILCs", "Tc", 
              "ILC1_NK", "NK", "Ttol", 
              "Plasma", "Bcell")

ct.cols <- c('#807dba','#9970ab','#810f7c', '#41ae76', 
             '#74add1', '#8dd3c7','#76d72f',
             '#f768a1', '#fdb462'
)

names(ct.cols) <- fac_levs

inteData$newCellType <- factor(inteData$newCellType, levels = fac_levs)

DimPlot(inteData, group.by = "newCellType", cols = ct.cols, label = T) + NoAxes()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = F, split.by = "Project", 
                 colors_use = ct.cols,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = T, split.by = "Condition", 
                 raster=FALSE, colors_use = ct.cols,
                 num_columns = 5) & NoLegend()

DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)

top_repre_markers <- c("CD3D", "CD3G", "KLRB1", "KLRD1", "CD4", "CD40LG", "CD8A", "CD8B",
                       "TIGIT", "BATF", "FOXP3", "CTLA4", "CORO1B", #cluster 5: Treg cells
                       "LDHB", "IL7R", "AP3M2", "GIMAP7", "KLF2", #cluster 0: Th cells
                       "AHR", "CCR6", "PTGER4", "ANKRD28", "LPAR6", #cluster 1: ILC cells
                       "FXYD2", "TRGC2", "KLRC3", "KLRC2","PDE4A", #cluster 7: Tc cells
                       "XCL1", "GNLY","XCL2", "FCER1G", #cluster 3: ILC1/NK cells
                       "NKG7", "GZMA","CRTAM", "GZMK", "TNFRSF9", #cluster 2: NK cells
                       "HSPA1B", "DNAJB1", "JUN", "FOS", "NR4A1", #cluster 4: Ttor cells
                       "PTGDS", "JCHAIN", "IL3RA", "CCR7", "CXCL8", #cluster 6: plasma cells
                       "IGKC", "MS4A1", "CD79A", "BANK1", "IGHM" #cluster 8: B cells
)

inteData$newCellType <- factor(inteData$newCellType, levels = rev(fac_levs))

plot_marker <- DotPlot(inteData, features = top_repre_markers, 
                       group.by = "newCellType", cols = c("white", "#cb181d"), 
                       dot.scale = 4,col.min = 0, dot.min = 0.05
) + theme(axis.text.x = element_text(angle = 90, hjust = 1),
          panel.border = element_rect(colour = "black", fill=NA)) + labs(x="", y="")
plot_marker

# Plot gene expression using RNA or SCT assay
FeaturePlot_scCustom(inteData,  features = c("CCR6"), split.by = "Condition", 
                     num_columns = 3)

# export the reduced results for quickly plotting
inteData@reductions$pca@assay.used <- "RNA"
inteData@reductions$harmony@assay.used <- "RNA"
inteData@reductions$umap@assay.used <- "RNA"

inteData <- DietSeurat(inteData, assays = "RNA", dimreducs = c("umap", "harmony"))

mt <- inteData@meta.data %>% rownames_to_column(var = "barcodeindex") %>% select(1:8,14:17,28,27,23,21,24,25,44,49)
data.table::fwrite(mt, "allacuteWound_DFU_VU_inteLymphoid_metadata.txt", sep = "\t")

mt_f <- mt %>% column_to_rownames(var = "barcodeindex")
inteData@meta.data <- mt_f
Idents(inteData) <- inteData$newCellType
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inteLymphoid_redu.rds"))
```

```{r}
library(scCustomize)
inteData <- readRDS("allacuteWound_DFU_VU_inteLymphoid_redu.rds")

FeaturePlot_scCustom(inteData,  features = c("TNF"), split.by = "Condition", 
                     num_columns = 3)
```

# SessionInfo
```{r}
sessionInfo()
```

