---
title: "integration of wound healing"
author: "Zhuang Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 6, warning=FALSE, message=FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(patchwork)
library(harmony)
```


# 1. Prepare wound data
```{r}
outname="Endo"
```

# 2. Integrate the human and VU, DFU chronic wound data
```{r eval=TRUE}
# vu data and acute wound data
vu_seu <- readRDS("../subCellTypeInte_acute_vu/allWound_acute_vu_integrated_Endo.rds")
DefaultAssay(vu_seu) = "RNA"
vu_seu <- DietSeurat(vu_seu, assays = "RNA")

# DFU data
hs_seu <- readRDS("../subCellTypeInte_acute_dfu/step6_DFU_Wound_inteotherEndo.rds")
hs_seu
hs_seu <- subset(hs_seu, subset= Project == "DFU")
DefaultAssay(hs_seu) = "RNA"
hs_seu <- DietSeurat(hs_seu, assays = "RNA")

# check the overlapped genes and keep the overlapped genes
overgene <- intersect(rownames(vu_seu), rownames(hs_seu))
length(overgene)

vu_seu <- vu_seu[overgene, ]
hs_seu <- hs_seu[overgene, ]

# integrate based on orig.ident names
#vu_seu$Project="VU"
#vu_seu$CellType=vu_seu$CellType
hs_seu$orig.ident=hs_seu$Donor1
#hs_seu$Project="DFU"
hs_seu$CellType=hs_seu$CellType
```

# 3. sctransform normalization
```{r eval=TRUE}
all_seu <- merge(vu_seu, y = c(hs_seu),
                project = "wounds")

rm(vu_seu);rm(hs_seu);gc()

alldata = SplitObject(all_seu, split.by = "orig.ident")
alldata <- lapply(X = alldata, FUN = function(x) {
  x <- NormalizeData(x)
  x <- CellCycleScoring(x, s.features = cc.genes.updated.2019$s.genes, g2m.features = cc.genes.updated.2019$g2m.genes, set.ident = F)
})
for (i in seq_along(alldata)) {
  alldata[[i]]$CC.Difference <- alldata[[i]]$S.Score - alldata[[i]]$G2M.Score
}

rm(all_seu)
alldata <- lapply(X = alldata, FUN = SCTransform, method = "glmGamPoi", vars.to.regress = c("CC.Difference"))
```


# 4. Run harmony Clustering
```{r eval=TRUE}
# Run harmony using SCTransform
options(future.globals.maxSize = 1000000 * 1024^2) 
features <- SelectIntegrationFeatures(object.list = alldata, nfeatures = 4000)

alldata <- PrepSCTIntegration(object.list = alldata, anchor.features = features)
inteData <- merge(alldata[[1]], y = c(alldata[2:length(alldata)]), merge.data = TRUE)
VariableFeatures(inteData) <- features
rm(alldata);gc()

inteData <- RunPCA(inteData, npcs = 50, assay = "SCT")
ElbowPlot(inteData, ndims = 50)
table(inteData$orig.ident)
# RunHarmony parameter: assay.use only for Seurat V3
inteData <- RunHarmony(inteData, #assay.use = "SCT", reduction = "pca", 
		       dims.use = 1:30, 
                       group.by.vars = "orig.ident", plot_convergence = TRUE)

inteData <- RunUMAP(inteData, dims = 1:30, assay = "SCT", reduction = "harmony", n.neighbors = 40)
DimPlot(inteData, group.by = "orig.ident") + NoAxes()

inteData = FindNeighbors(inteData, dims = 1:30, reduction = "harmony", k.param = 40)
inteData = FindClusters(inteData, resolution = 0.3)
inteData = FindClusters(inteData, resolution = 1)
inteData = FindClusters(inteData, resolution = 1.5)
inteData = FindClusters(inteData, resolution = 1.2)
inteData = FindClusters(inteData, resolution = 0.5)
inteData = FindClusters(inteData, resolution = 0.8)

inteData$Condition <- factor(inteData$Condition, levels = c("Skin", "Wound1", "Wound7", "Wound30","H", "DFU_NH", "DFU_H", "NS", "VU"))

DimPlot(inteData, group.by = "SCT_snn_res.1", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.5", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.8", label = T, raster=FALSE)
DimPlot(inteData, group.by = "SCT_snn_res.0.8", label = T, split.by = "Condition", raster=FALSE)  
DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)
```


# 5. CellType plotting
```{r fig.width=12, fig.height=8}
DimPlot(inteData, group.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 
DimPlot(inteData, group.by = "Project", split.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 


DimPlot(inteData, group.by = "CellType", label = T, split.by = "Project", raster=FALSE) + ggtitle("")
DimPlot(inteData, group.by = "CellType", label = T, split.by = "Condition", ncol = 4, raster=FALSE) + ggtitle("") + NoLegend()
```


# 6. Data exporting
```{r}
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inte", outname, ".rds"))

# export the reduced results for quickly plotting
inteData@reductions$pca@assay.used <- "RNA"
inteData@reductions$harmony@assay.used <- "RNA"
inteData@reductions$umap@assay.used <- "RNA"

inteData <- DietSeurat(inteData, assays = "RNA", dimreducs = c("umap"))
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inte", outname, "_redu.rds"))
```


# manuscript plotting
```{r eval=FALSE}
#If you are using Seurat V5 but do not want to use the V5 Assay, 
#you can set the option to "v3"
options(Seurat.object.assay.version = 'v3')

library(scCustomize)
library(Seurat)
library(SeuratObject)
library(tidyverse)
library(patchwork)
library(ggplot2)

inteData <- readRDS("allacuteWound_DFU_VU_inteEndo.rds")
inteData
DimPlot(inteData, group.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE) 
DimPlot(inteData, group.by = "Project", split.by = "Project", cols = c("#fc8d59", "#d8b365", "#5ab4ac"), raster=FALSE)

DimPlot(inteData, group.by = "CellType", label = T, split.by = "Project", raster=FALSE) + ggtitle("") + NoLegend()
DimPlot(inteData, group.by = "CellType", label = T, split.by = "Condition", ncol = 4, raster=FALSE) + ggtitle("") + NoLegend()
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 raster=F, #pt.size = 1, 
                 ggplot_default_colors = TRUE,
                 label.size = 4,
                 num_columns = 3) & NoLegend()

DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)

FeaturePlot_scCustom(inteData,  features = c("COL1A2"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KRT1"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("COL1A1"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KRT10"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KRT5"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("KRT14"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot_scCustom(inteData,  features = c("MKI67"), split.by = "Condition", 
                     num_columns = 3)
table(inteData$Condition, inteData$SCT_snn_res.1)
table(inteData$CellType, inteData$SCT_snn_res.1)

DefaultAssay(inteData) <- "SCT"
inteData = FindClusters(inteData, resolution = 1.5)
inteData = FindClusters(inteData, resolution = 1.8)
inteData = FindClusters(inteData, resolution = 3)
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.3", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.3", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

# remove some inconsistent clusters or doublets through checking some markers below
inteData$fil <- ifelse(inteData$SCT_snn_res.1 %in% c(15), "keep", "no")
inteData <- subset(inteData, subset = fil == "no")
inteData@meta.data <- droplevels(inteData@meta.data)

table(inteData$CellType, inteData$SCT_snn_res.3)

### re-run the UMAP
#inteData <- RunUMAP(inteData, dims = 1:30, assay = "SCT", reduction = "harmony", n.neighbors = 40, n.epochs = 500)

DimPlot(inteData, group.by = "SCT_snn_res.3", label = T)
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.3", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "SCT_snn_res.3", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Project", 
                 ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "CellType", 
                 label = T, split.by = "Condition", 
                 raster=FALSE, label.size = 4, ggplot_default_colors =T,
                 num_columns = 3) & NoLegend()

DefaultAssay(inteData) <- "RNA"
FeaturePlot_scCustom(inteData,  features = c("ADRA2A"), split.by = "Condition", 
                     num_columns = 3)
FeaturePlot(inteData,  features = c("MKI67"), cols = c("grey90", "red"))

Idents(inteData) <- inteData$SCT_snn_res.1.5
Cluster_Highlight_Plot(seurat_object = inteData, 
                       cluster_name = c("8","14","13","11"), #12,20,25,27,29
                       highlight_color = c("navy","forestgreen", "red", "pink"),
                       background_color = "lightgray")
table(inteData$CellType, inteData$SCT_snn_res.1.8)
table(inteData$SCT_snn_res.0.8, inteData$SCT_snn_res.1.8)

Idents(inteData) <- inteData$CellType
Cluster_Highlight_Plot(seurat_object = inteData, 
                       cluster_name = c("Mac_inf","Mac1","Mac2", "Mac3"), 
                       highlight_color = c("red", "navy","forestgreen", "pink"),
                       background_color = "lightgray")

# re-annotate the cell clusters based on 1.5
anno.cl <- list()
anno.cl$SMC = c(1,2,8,19,11) 
anno.cl$Pericytes = c(9,15,27,6,24,18,7,21,23,26,28,16,17,13,20) 
anno.cl$LE = c(10) 
anno.cl$VE_arteriole = c(5) 
anno.cl$VE_capillary = c(14) 
anno.cl$VE_venule1 = c(0,25,4,22) 
anno.cl$VE_venule2 = c(3,12) 

trans = rep(names(anno.cl), times = unlist(lapply(anno.cl, length)))
names(trans) = unlist(anno.cl)
mt <- inteData@meta.data
mt$newCellType <- trans[as.character(mt$SCT_snn_res.3)]
inteData$newCellType <- mt$newCellType
table(inteData$newCellType)
DimPlot(inteData, group.by = "newCellType", label = T) + NoAxes()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = T, split.by = "Condition", 
                 ggplot_default_colors =T, label.size = 3,
                 num_columns = 3) & NoLegend()

table(inteData$newCellType, inteData$Condition)
table(inteData$CellType, inteData$SCT_snn_res.3)


fac_levs <- c("SMC", "Pericytes", "LE",
              "VE_arteriole", "VE_capillary",
              "VE_venule1", "VE_venule2")
ct.cols <- c('#12a22d', '#ce8b1a', '#fe8Bac', 
             '#d93860', '#3ba4db', 
             '#807dba', '#d4b9da')
names(ct.cols) <- fac_levs

inteData$newCellType <- factor(inteData$newCellType, levels = fac_levs)

DimPlot(inteData, group.by = "newCellType", cols = ct.cols, label = T) + NoAxes()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = F, split.by = "Project", 
                 colors_use = ct.cols,
                 num_columns = 3) & NoLegend()
DimPlot_scCustom(inteData,  group.by = "newCellType", 
                 label = F, split.by = "Condition", 
                 raster=FALSE, colors_use = ct.cols,
                 num_columns = 5) & NoLegend()

DefaultAssay(inteData) <- "RNA"
inteData <- NormalizeData(inteData)

top_repre_markers <- c("ACTA2", "TAGLN", "MYH11", "ADRA2A", "MUSTN1", # SMC
                       "COL6A3", "COL5A2", "THY1", "DCN", "GUCY1A2", # Pericytes
                       "CCL21", "TFF3", "LYVE1", "PDPN", # LE
                       "PECAM1","IGFBP3", "ARL15", "CXCL12", "HEY1", "SEMA3G", # VE_arteriole
                       "COL15A1", "VWA1", "RGCC", "H19", "APLN", # VE_capillary
                       "G0S2", "SELE", "ACKR1", "CSF3", "STC1", # VE_venule1
                       "CCL14", "AQP1", "ID1", "SOX18", "SNCG" # VE_venule2
)

inteData$newCellType <- factor(inteData$newCellType, levels = rev(fac_levs))

plot_marker <- DotPlot(inteData, features = top_repre_markers, 
                       group.by = "newCellType", cols = c("white", "#cb181d"), 
                       dot.scale = 4, col.min = 0, dot.min = 0.05
) + theme(axis.text.x = element_text(angle = 90, hjust = 1),
          panel.border = element_rect(colour = "black", fill=NA)) + labs(x="", y="")
plot_marker

# export the reduced results for quickly plotting
inteData@reductions$pca@assay.used <- "RNA"
inteData@reductions$harmony@assay.used <- "RNA"
inteData@reductions$umap@assay.used <- "RNA"

inteData <- DietSeurat(inteData, assays = "RNA", dimreducs = c("umap", "harmony"))

mt <- inteData@meta.data %>% rownames_to_column(var = "barcodeindex") %>% select(1:8,14:17,32,31,28,27,25,36,49,51)
data.table::fwrite(mt, "allacuteWound_DFU_VU_inteEndo_metadata.txt", sep = "\t")

mt_f <- mt %>% column_to_rownames(var = "barcodeindex")
inteData@meta.data <- mt_f
Idents(inteData) <- inteData$newCellType
saveRDS(inteData, file=paste0("allacuteWound_DFU_VU_inteEndo_redu.rds"))
```


# SessionInfo
```{r}
sessionInfo()
```

