---
title: "Marker genes featureplot resolution 0.3"
author: "Zhuang Liu"
date: "02/12/2021 Updated: `r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 8, warning=FALSE, message=FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(cowplot)
```

####################################################
# Step. Marker genes identification
####################################################
## S. Known marker genes
```{r fig.width=9, fig.height=6}
inteData <- readRDS("all_HsMs_CCA_W1_DPW3_sampling_noSkin.rds")
# UMAP changes a bit (n.epochs = 200)
inteData <- RunUMAP(inteData, dims = 1:30, assay = "integrated", reduction = "pca", n.neighbors = 40,
                    min.dist = 0.5, n.epochs = 500, spread = 1, learning.rate = 1)


DimPlot(inteData, group.by = "CellType", label = T, split.by = "Condition", ncol = 4) + ggtitle("") + NoLegend()
DimPlot(inteData, group.by = "integrated_snn_res.0.3", label = T, split.by = "Condition", ncol = 4) + ggtitle("") + NoLegend()
FeaturePlot(inteData, features = c("IL24"), split.by = "Condition", cols = c("grey90", "red"), order = T)
VlnPlot(inteData, features = c("IL24"), group.by = "integrated_snn_res.0.3", split.by = "Condition")

FeaturePlot(inteData, features = c("FOSL1"), split.by = "Condition", cols = c("grey90", "red"), order = T, pt.size = 0.8, min.cutoff = 0.1)
VlnPlot(inteData, features = c("FOSL1"), group.by = "integrated_snn_res.0.3", split.by = "Condition")

table(inteData$CellType, inteData$integrated_snn_res.0.3)
table(inteData$CellType, inteData$integrated_snn_res.0.5)
table(inteData$CellType, inteData$integrated_snn_res.0.8)

FeaturePlot(inteData, features = c("IL24", "GJB2", "FOSL1", "ITGA5"), split.by = "Condition", cols = c("grey90", "red"))
FeaturePlot(inteData, features = c("IL24"), split.by = "Condition", cols = c("grey90", "red"), order = T)
```

## S. Visualizing marker genes for each cluster
```{r fig.width=12, fig.height=30}
DefaultAssay(inteData) <- "RNA"
markers <- data.table::fread("all_HsMs_CCA_W1_DPW3_sampling_withSkin_0.3Marker.txt")

markers_top10 <- markers %>% group_by(cluster) %>% top_n(10, avg_log2FC)
fac_levs <- unique(markers$cluster)

plot_list <- list()
for (i in seq_along(fac_levs)) {
  #print(paste0("Cluster ", i, " :Top 10 marker genes"))
  names <- fac_levs[i]
  plot_list[[i]] <- DotPlot(inteData, features = markers_top10[markers_top10$cluster == names, ]$gene, col.max = 5, col.min = 0, 
                                dot.scale = 4, dot.min = 0.1,
                                assay = "RNA", group.by = "integrated_snn_res.0.3") + RotatedAxis() + coord_flip() + xlab("Marker genes") + ylab("") +
    theme(axis.text.x=element_text(size=10), axis.text.y=element_text(size=10)) + ggtitle(label = names)
}

wrap_plots(plot_list,ncol = 2) #+ plot_layout(guides = 'collect') & theme(legend.position = 'right')
```

## S. featurePlot Visualizing marker genes for each cluster
```{r fig.height=14}
markers_top10 <- markers %>% group_by(cluster) %>% top_n(20, avg_log2FC)
fac_levs <- unique(markers$cluster)

for (i in seq_along(fac_levs)) {
  print(paste0("Plot cluster", i-1))
  names <- fac_levs[i]
  plotgenes= markers_top10[markers_top10$cluster == names, ]$gene
  plot_list <- FeaturePlot(
    inteData,
    features=plotgenes,
    combine=FALSE, cols = c("gray","red")
  )
  # apply theme to each feature plot
  for(i in 1:length(plot_list)){
    plot_list[[i]] <- plot_list[[i]] + NoLegend() + NoAxes()
  }
  print(wrap_plots(plot_list, ncol = 5))
}
```


# SessionInfo
```{r}
sessionInfo()
```
