---
title: "Add the Neutrophil cells"
author: "Zhuang Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width = 12, warning = FALSE, message = FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(harmony)
```


##########################
# Step 1. Extract cells
##########################
## 1.1 Load the whole cell types
```{r fig.width=8, fig.height=6}
sms <- dir(path = ".", pattern = "^PWH")
sm_folders <- paste0("./", sms, "/raw_feature_bc_matrix.h5")

sceList <- list()
for (i in seq_along(sms)) {
  tmp_sms <- sms[i]
  tmp = Read10X_h5(sm_folders[i])
  nE = colSums(tmp > 0)
  tmp = tmp[, nE >= 100]

  sceList[[tmp_sms]] = tmp
}

metadata <- readxl::read_xlsx("/Users/zhuliu/Desktop/scRNA_STseq/proj_10X_woundhealing/02_metadata/Metadata_STsc.xlsx") %>% slice(17:28)
metadata <- metadata %>% select(3:6,11) %>% mutate(User_ID = gsub("_","",User_ID)) %>% rename(ID=User_ID)
cols.keep = colnames(metadata)

for (sample in sms) {
    m = match(sample, metadata$ID)
    meta.tmp = data.frame(row.names = colnames(sceList[[sample]]))
    for (cname in cols.keep) {
        meta.tmp[[cname]] = as.character(metadata[m, cname])
    }
    sceList[[sample]] = CreateSeuratObject(sceList[[sample]], meta.data = meta.tmp)
}

data = merge(sceList[[1]], sceList[2:length(sceList)], add.cell.ids = sms, project = "humanWounds")

rm(sceList, meta.tmp, metadata, tmp);invisible(gc())


data$ID <- as.character(data$ID)
data$Condition <- ifelse(data$ID %in% c("PWH26D0", "PWH27D0", "PWH28D0"), "Skin", data$ID)
data$Condition <- ifelse(data$Condition %in% c("PWH26D1", "PWH27D1", "PWH28D1"), "Wound1", data$Condition)
data$Condition <- ifelse(data$Condition %in% c("PWH26D7", "PWH27D7", "PWH28D7"), "Wound7", data$Condition)
data$Condition <- ifelse(data$Condition %in% c("PWH26D30", "PWH27D30", "PWH28D30"), "Wound30", data$Condition)
data$ID <- factor(x = data$ID, levels =
                       c("PWH26D0", "PWH26D1", "PWH26D7","PWH26D30",
                         "PWH27D0", "PWH27D1", "PWH27D7","PWH27D30",
                         "PWH28D0", "PWH28D1", "PWH28D7","PWH28D30"))
data$Condition <- factor(x = data$Condition, levels =
                              c("Skin", "Wound1", "Wound7","Wound30"))
table(data$ID)
table(data$Condition)
```


## 1.2 Quality control
```{r}
data@active.ident = factor(data$ID)

# neutrophil markers
# markers neut.genes = c("CSF3R", "FPR1", "NAMPT", "MNDA", "G0S2") from PMID: 33494096
# but these markers are not specifically expressed
neut.genes = c("FCGR3B", "CMTM2", "CXCR2", "PROK2", "LINC01506") #"LCN2", 

data <- PercentageFeatureSet(data, "^MT-", col.name = "percent_mito")
data <- PercentageFeatureSet(data, "^RP[SL]", col.name = "percent_ribo")
data <- PercentageFeatureSet(data, "^HB[^(PES)]", col.name = "percent_hb")
data <- PercentageFeatureSet(data, "MALAT1", col.name = "percent_malat1")
data <- PercentageFeatureSet(data, features = neut.genes, col.name = "percent_neut")

VlnPlot(data, features = c("nCount_RNA"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("nFeature_RNA"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("percent_mito"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("percent_hb"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("percent_ribo"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("percent_malat1"), pt.size = 0.1) + NoLegend()
VlnPlot(data, features = c("percent_neut"), pt.size = 0.1) + NoLegend()

data$Neut = ifelse(data$percent_neut > 0, "Neut", "Other")
table(data$Neut, data$ID)
table(data$ID)

VlnPlot(data, features = neut.genes, group.by = "Neut")

data = NormalizeData(data)
VlnPlot(data, features = neut.genes, group.by = "Neut", ncol = 5)
```


## 1.3 Extract putative neutrophil cells
```{r}
#neulist <- readRDS("s1_clean_neutrophils.rds")
#ndata <- neulist$ndata
#ndata2 <- neulist$ndata2

ndata = data[, data$Neut == "Neut"]
#rm(data)

# filter mito,malat and hb genes
ndata <- ndata[!grepl("^MT-", rownames(ndata)), ]
ndata <- ndata[!grepl("^HB[^(PES)]", rownames(ndata)), ]
ndata <- ndata[!grepl("MALAT1", rownames(ndata)), ]

ndata = NormalizeData(ndata)

VlnPlot(ndata, features = neut.genes)
VlnPlot(ndata, features = c("nFeature_RNA", "nCount_RNA"))

ndata = FindVariableFeatures(ndata, verbose = F)
ndata = ScaleData(ndata, verbose = F, vars.to.regress = c("nFeature_RNA", "nCount_RNA"))
ndata = RunPCA(ndata, verbose = F)
ElbowPlot(ndata, ndims = 30, reduction = "pca")

ndata = RunUMAP(ndata, dims = 1:20, verbose = F)
ndata = FindNeighbors(ndata, dims = 1:20, verbose = F)
ndata = FindClusters(ndata, resolution = 0.3, verbose = F)

ndata$ID <- as.character(ndata$ID)
ndata$Condition <- ifelse(ndata$ID %in% c("PWH26D0", "PWH27D0", "PWH28D0"), "Skin", ndata$ID)
ndata$Condition <- ifelse(ndata$Condition %in% c("PWH26D1", "PWH27D1", "PWH28D1"), "Wound1", ndata$Condition)
ndata$Condition <- ifelse(ndata$Condition %in% c("PWH26D7", "PWH27D7", "PWH28D7"), "Wound7", ndata$Condition)
ndata$Condition <- ifelse(ndata$Condition %in% c("PWH26D30", "PWH27D30", "PWH28D30"), "Wound30", ndata$Condition)
table(ndata$Condition)

ndata$ID <- factor(x = ndata$ID, levels =
                       c("PWH26D0", "PWH26D1", "PWH26D7","PWH26D30",
                         "PWH27D0", "PWH27D1", "PWH27D7","PWH27D30",
                         "PWH28D0", "PWH28D1", "PWH28D7","PWH28D30"))
ndata$Condition <- factor(x = ndata$Condition, levels =
                              c("Skin", "Wound1", "Wound7","Wound30"))

p1 = DimPlot(ndata, label = T) + NoAxes()
p2 = DimPlot(ndata, group.by = "ID") + NoAxes()
p3 = DimPlot(ndata, group.by = "Condition") + NoAxes()
p4 = FeaturePlot(ndata, "percent_neut") + NoAxes() 
wrap_plots(list(p1, p2, p3, p4), ncol = 2)

FeaturePlot(ndata, features = c("CSF3R", "FPR1", "NAMPT", "MNDA", "G0S2",
                                 "FCGR3B", "CMTM2", "CXCR2", "PROK2", "LINC01506", "LCN2",
                                 "IL1B", "MMP9"), order = T)

table(ndata$ID[ndata$seurat_clusters %in% c(1,8)])
table(ndata$Condition[ndata$seurat_clusters %in% c(1,8)])
pdf("Raw.pdf", useDingbats = F, width = 12, height = 3)
VlnPlot(ndata, features = c("nFeature_RNA", "nCount_RNA"))
dev.off()
p = FeaturePlot(ndata, features = neut.genes, combine = F, order = T)
wrap_plots(p, ncol = 2)
```

## 1.4 Take only neutrophil clusters
```{r}
ndata2 = ndata[, ndata$seurat_clusters %in% c(1, 8)]

ndata2 = FindVariableFeatures(ndata2)
ndata2 = ScaleData(ndata2)
ndata2 = RunPCA(ndata2)
ElbowPlot(ndata2, ndims = 20, reduction = "pca")

ndata2 = RunUMAP(ndata2, dims = 1:15)
ndata2 = FindNeighbors(ndata2, dims = 1:15)
ndata2 = FindClusters(ndata2, resolution = 0.3)

p1 = DimPlot(ndata2, label = T) + NoAxes()
p2 = DimPlot(ndata2, group.by = "ID") + NoAxes()
p3 = DimPlot(ndata2, group.by = "Condition") + NoAxes()
p4 = FeaturePlot(ndata2, "percent_neut") + NoAxes() 
wrap_plots(list(p1, p2, p3, p4), ncol = 2)
pdf("Clean.pdf", useDingbats = F, width = 10, height = 8)
wrap_plots(list(p1, p2, p3, p4), ncol = 2)
dev.off()

p = FeaturePlot(ndata2, features = neut.genes, combine = F, order = T)
wrap_plots(p, ncol = 2)

markers = FindAllMarkers(ndata2, assay = "RNA", only.pos = T, verbose = F)
top10 <- markers %>%
    group_by(cluster) %>% arrange(cluster, desc(avg_log2FC)) %>% 
    slice(1:10) %>% ungroup()

DotPlot(ndata2, assay = "RNA", features = unique(top10$gene)) + RotatedAxis()

FeaturePlot(ndata2, features = c("percent_mito", "percent_ribo", "percent_hb", "percent_neut", "percent_malat1"), ncol = 3)
VlnPlot(ndata2, features = c("nFeature_RNA", "nCount_RNA"))
table(ndata2$nFeature_RNA > 500)
table(ndata2$seurat_clusters, ndata2$Condition)
table(ndata2$seurat_clusters, ndata2$ID)

pdf("Clean_markers.pdf", useDingbats = F, width = 10, height = 8)
FeaturePlot(ndata2, features = c("CSF3R", "FPR1", "NAMPT", "MNDA", "G0S2",
                                 "FCGR3B", "CMTM2", "CXCR2", "PROK2"),
            cols = c("grey90", "red"), ncol = 3, order = T)
dev.off()

#markers_f <- markers %>% arrange(cluster, desc(avg_log2FC))
neulist <- list(ndata, ndata2)
names(neulist) <- c("ndata", "ndata2")
saveRDS(neulist, file = "s1_clean_neutrophils.rds")
```

```{r}
df <- table(ndata2$seurat_clusters, ndata2$Condition) %>% as.data.frame() %>% setNames(c("Cluster", "Group", "CellNumber"))
df$Cluster <- gsub(0, "Neut0", df$Cluster)
df$Cluster <- gsub(1, "Neut1", df$Cluster)

pdf("CleanCellNumber.pdf", useDingbats = F, width = 6, height = 2)
ggplot(df, aes(x=Cluster, y=CellNumber, fill=Group)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text.x = element_text(size= 12),
      axis.title.x = element_text(size= 12),
      axis.text.y = element_text(size= 12),
      axis.title.y = element_text(size= 12),
      axis.title=element_text(size=12), #face = "bold"
      plot.title = element_text(size = 12)
    )
dev.off()
```




```{r}
df <- data.frame(table(ndata2$Condition) /table(data$Condition)) %>% mutate(p = Freq/sum(Freq), lbl = scales::percent(p), Sample = "Neutrophils") %>% 
  rename("Condition" = "Var1")

p_cp_5 <- ggplot(df, aes(x = Sample, y = p, fill = Condition)) +
  geom_bar(position = "fill", stat = "identity") +
  xlab('') +
  scale_fill_manual(values = c("#4dbbd5", "#ce8b1a", "#de77ae", "#00a087")) + 
  scale_y_continuous(breaks = seq(0, 1, .2), 
                     expand = c(0, 0.01),
                     labels = c("0%", "20%", "40%", "60%", "80%", "100%"),
                     name = 'Percentage') +
  geom_text(aes(label = lbl), 
            size = 4, 
            position = position_stack(vjust = 0.5)) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_blank(),
    axis.text.x = element_text(size = 14, color = "black", angle = 45, hjust = 1),
    axis.text.y = element_text(size = 14, color = "black"),
    axis.title.y = element_text(size = 16, color = "black"),
    legend.position = "right",
    legend.text = element_text(size = 12, color = "black")
  ) 
p_cp_5
```


```{r eval=FALSE, fig.height=11}
FeaturePlot(
  ndata.com,
  features=c('CD14', 'S100A9', 'FCGR3A', 'IL1B', 'CD163'), 
  combine=T, cols = c("grey","red")
)

plotcom <- FeaturePlot(
  ndata.com,
  features=c('CD68', 'CD163', 'CD14', 'CD209', 'FCGR2A', 'MRC1', 'CD207', 'CD1A', 'CD1C', 'CD1B', 'ITGAX', 
             'CD83', 'LAMP3', 'THBD', 'CLEC9A', 'MKI67'), 
  combine=F, cols = c("grey","red")
)

# apply theme to each feature plot
for(i in 1:length(plotcom)){
  plotcom[[i]] <- plotcom[[i]] + NoLegend() + NoAxes()
}

cowplot::plot_grid(plotlist = plotcom, ncol = 4)
```

# SessionInfo
```{r}
sessionInfo()
```
