---
title: "Nichenet ligand-receptor analysis"
author: "Zhuang Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 8)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(multinichenetr)
```


#########################################
# Step 5. Load and visualize the results
##############################################################
# Circos plot of top ligand and recepter pairs for each group
```{r}
multinichenet_output <- readRDS("multinichenet_output.rds")

lr_ligand <- multinichenet_output$lr_target_prior_cor %>% dplyr::filter(receiver == "Bas_mig" | receiver == "Spi_mig") %>% 
  dplyr::filter(rank_of_target < 250)

multinichenet_output$celltype_de$cluster_id %>% unique()

# choose the group and receiver cell types we are interested
prioritized_tbl_oi_all = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                            top_n = 50, 
                                            groups_oi = "Wound30",
                                            senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                            receivers_oi = c("Bas_mig", "Spi_mig"),
                                            rank_per_group = F)

prioritized_tbl_oi = multinichenet_output$prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% left_join(prioritized_tbl_oi_all)
prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] = 0

senders_receivers = union(prioritized_tbl_oi$sender %>% unique(), prioritized_tbl_oi$receiver %>% unique()) %>% sort()

fac_lev <- c("M1", "Mac_inf", "Mac_mig", "M2", 
              "cDC1", "cDC2", "DC3", "LC", 
              "Bas_mig", "Spi_mig")
ct.cols <- c('#df65b0', '#f1b6da','#addd8e','#41ab5d', 
             "#807dba", "#9970ab", "#b2abd2", "#bf812d",
             '#ccebc5', '#b3de69')
names(ct.cols) <- fac_lev

colors_sender = ct.cols[match(senders_receivers, names(ct.cols))]
colors_sender = colors_sender[order(match(names(colors_sender), fac_lev))]

colors_receiver = ct.cols[match(c("Bas_mig", "Spi_mig"), names(ct.cols))]
colors_receiver = colors_receiver[order(match(names(colors_receiver), fac_lev))]
#RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)

# reset the fators of groups and cell types
#prioritized_tbl_oi$group <- factor(prioritized_tbl_oi$group, levels = c("Skin", "Wound1", "Wound7", "Wound30"))
prioritized_tbl_oi <- prioritized_tbl_oi %>% dplyr::slice(1:50) # if you only interested in one group

prioritized_tbl_oi$sender <- factor(prioritized_tbl_oi$sender, levels = names(colors_sender))
prioritized_tbl_oi$receiver <- factor(prioritized_tbl_oi$receiver, levels = names(colors_receiver))

circos_list = make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)

#pdf(file = "Top50_L_R_pairs_Wound30_circos.pdf", height = 8, width = 8, useDingbats = F)
circos_list = make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)
#dev.off()
```


###################################################################
# Plot the average expression of ligand and recepter for each group
```{r fig.height=12}

ligand_activity <- multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl
group_lr <- multinichenet_output$prioritization_tables$group_prioritization_tbl

print("Wound1 - Receiver: Bas-mig, Spi-mig")
# Visualization of scaled ligand-receptor pseudobulk products and ligand activity
prioritized_tbl_oi_wound1 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                              top_n = 50, 
                                              groups_oi = "Wound1",
                                              senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                              receivers_oi = c("Bas_mig", "Spi_mig"))

plot_oi = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_wound1)
plot_oi

######################################################
# make the plot by myself (refer to the source code)
sample_data = multinichenet_output$prioritization_tables$sample_prioritization_tbl %>%
  dplyr::filter(id %in% prioritized_tbl_oi_wound1$id) %>% 
  dplyr::mutate(sender_receiver = paste(sender, receiver, sep = " --> "), 
                lr_interaction = paste(ligand, receptor, sep = " - ")) %>% 
  dplyr::arrange(receiver) %>% dplyr::group_by(receiver) %>% dplyr::arrange(sender, .by_group = TRUE)

# Check the names of facotr
fact_lev <- sample_data$sender_receiver %>% unique()
fact_lev <- fact_lev[c(3,5,6,4,1,2,10,12,11,7:9)]
# set the factor
sample_data = sample_data %>% dplyr::mutate(sender_receiver = factor(sender_receiver, levels = fact_lev))
sample_data = sample_data %>% dplyr::mutate(group = factor(group, levels = c("Skin", "Wound1", "Wound7", "Wound30")))

########################
# Sample expression plot
p1 = sample_data %>% ggplot(aes(sample, lr_interaction, color = scaled_LR_pb_prod, size = keep_sender_receiver)) + 
  geom_point() + 
  facet_grid(sender_receiver ~ group, scales = "free",
             space = "free", switch = "y") + 
  scale_x_discrete(position = "top") + 
  theme_light() + theme(axis.ticks = element_blank(), 
                        axis.title = element_blank(), 
                        axis.text.y = element_text(face = "bold.italic", size = 9), 
                        axis.text.x = element_text(size = 9, angle = 90, hjust = 0), 
                        panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(), 
                        panel.spacing.x = unit(0.4, "lines"), 
                        panel.spacing.y = unit(0.25, "lines"), 
                        strip.text.x.top = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) +
  labs(color = "Scaled average\nL-R expression", size = "Average fraction of\nL-R expression") + 
  scale_size_manual(values = keep_sender_receiver_values)

max_lfc = abs(sample_data$scaled_LR_pb_prod) %>% max()
custom_scale_fill = scale_color_gradientn(colours = RColorBrewer::brewer.pal(n = 7, 
  name = "RdBu") %>% rev(), values = c(0, 0.35, 0.485, 
  0.5, 0.515, 0.65, 1), limits = c(-1 * max_lfc, max_lfc))
p1 = p1 + custom_scale_fill
p1
pdf(file = "Top50_L_R_pairs_Wound1.pdf", height = 10, width = 8, useDingbats = F)
p1
dev.off()


#############################################
print("Wound7 - Receiver: Bas-mig, Spi-mig")
# Visualization of scaled ligand-receptor pseudobulk products and ligand activity
prioritized_tbl_oi_wound7 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                              top_n = 50, 
                                              groups_oi = "Wound7",
                                              senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                              receivers_oi = c("Bas_mig", "Spi_mig"))

plot_oi_wound7 = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_wound7)
plot_oi_wound7

######################################################
# make the plot by myself (refer to the source code)
sample_data = multinichenet_output$prioritization_tables$sample_prioritization_tbl %>%
  dplyr::filter(id %in% prioritized_tbl_oi_wound7$id) %>% 
  dplyr::mutate(sender_receiver = paste(sender, receiver, sep = " --> "), 
                lr_interaction = paste(ligand, receptor, sep = " - ")) %>% 
  dplyr::arrange(receiver) %>% dplyr::group_by(receiver) %>% dplyr::arrange(sender, .by_group = TRUE)

# Check the names of facotr
fact_lev <- sample_data$sender_receiver %>% unique()
fact_lev
fact_lev <- fact_lev[c(4,6,7,5,1,2,9,11:12,10)]
# set the factor
sample_data = sample_data %>% dplyr::mutate(sender_receiver = factor(sender_receiver, levels = fact_lev))
sample_data = sample_data %>% dplyr::mutate(group = factor(group, levels = c("Skin", "Wound1", "Wound7", "Wound30")))

########################
# Sample expression plot
p1 = sample_data %>% ggplot(aes(sample, lr_interaction, color = scaled_LR_pb_prod, size = keep_sender_receiver)) + 
  geom_point() + 
  facet_grid(sender_receiver ~ group, scales = "free",
             space = "free", switch = "y") + 
  scale_x_discrete(position = "top") + 
  theme_light() + theme(axis.ticks = element_blank(), 
                        axis.title = element_blank(), 
                        axis.text.y = element_text(face = "bold.italic", size = 9), 
                        axis.text.x = element_text(size = 9, angle = 90, hjust = 0), 
                        panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(), 
                        panel.spacing.x = unit(0.4, "lines"), 
                        panel.spacing.y = unit(0.25, "lines"), 
                        strip.text.x.top = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) +
  labs(color = "Scaled average\nL-R expression", size = "Average fraction of\nL-R expression") + 
  scale_size_manual(values = keep_sender_receiver_values)

max_lfc = abs(sample_data$scaled_LR_pb_prod) %>% max()
custom_scale_fill = scale_color_gradientn(colours = RColorBrewer::brewer.pal(n = 7, 
  name = "RdBu") %>% rev(), values = c(0, 0.35, 0.485, 
  0.5, 0.515, 0.65, 1), limits = c(-1 * max_lfc, max_lfc))
p1 = p1 + custom_scale_fill
p1
pdf(file = "Top50_L_R_pairs_Wound7.pdf", height = 10, width = 8, useDingbats = F)
p1
dev.off()


##############################################
print("Wound30 - Receiver: Bas-mig, Spi-mig")
# Visualization of scaled ligand-receptor pseudobulk products and ligand activity
prioritized_tbl_oi_wound30 = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                              top_n = 50, 
                                              groups_oi = "Wound30",
                                              senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                              receivers_oi = c("Bas_mig", "Spi_mig"))

plot_oi_wound30 = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_wound30)
plot_oi_wound30

######################################################
# make the plot by myself (refer to the source code)
sample_data = multinichenet_output$prioritization_tables$sample_prioritization_tbl %>%
  dplyr::filter(id %in% prioritized_tbl_oi_wound30$id) %>% 
  dplyr::mutate(sender_receiver = paste(sender, receiver, sep = " --> "), 
                lr_interaction = paste(ligand, receptor, sep = " - ")) %>% 
  dplyr::arrange(receiver) %>% dplyr::group_by(receiver) %>% dplyr::arrange(sender, .by_group = TRUE)

# Check the names of facotr
fact_lev <- sample_data$sender_receiver %>% unique()
fact_lev
fact_lev <- fact_lev[c(5,7,8,6,1:4,13,15,16,14,9:12)]
# set the factor
sample_data = sample_data %>% dplyr::mutate(sender_receiver = factor(sender_receiver, levels = fact_lev))
sample_data = sample_data %>% dplyr::mutate(group = factor(group, levels = c("Skin", "Wound1", "Wound7", "Wound30")))

########################
# Sample expression plot
p1 = sample_data %>% ggplot(aes(sample, lr_interaction, color = scaled_LR_pb_prod, size = keep_sender_receiver)) + 
  geom_point() + 
  facet_grid(sender_receiver ~ group, scales = "free",
             space = "free", switch = "y") + 
  scale_x_discrete(position = "top") + 
  theme_light() + theme(axis.ticks = element_blank(), 
                        axis.title = element_blank(), 
                        axis.text.y = element_text(face = "bold.italic", size = 9), 
                        axis.text.x = element_text(size = 9, angle = 90, hjust = 0), 
                        panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(), 
                        panel.spacing.x = unit(0.4, "lines"), 
                        panel.spacing.y = unit(0.25, "lines"), 
                        strip.text.x.top = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) +
  labs(color = "Scaled average\nL-R expression", size = "Average fraction of\nL-R expression") + 
  scale_size_manual(values = keep_sender_receiver_values)

max_lfc = abs(sample_data$scaled_LR_pb_prod) %>% max()
custom_scale_fill = scale_color_gradientn(colours = RColorBrewer::brewer.pal(n = 7, 
  name = "RdBu") %>% rev(), values = c(0, 0.35, 0.485, 
  0.5, 0.515, 0.65, 1), limits = c(-1 * max_lfc, max_lfc))
p1 = p1 + custom_scale_fill
p1
pdf(file = "Top50_L_R_pairs_Wound30.pdf", height = 10, width = 8, useDingbats = F)
p1
dev.off()


##########################################
print("Skin - Receiver: Bas-mig, Spi-mig")
# Visualization of scaled ligand-receptor pseudobulk products and ligand activity
prioritized_tbl_oi_Skin = get_top_n_lr_pairs(multinichenet_output$prioritization_tables, 
                                              top_n = 50, 
                                              groups_oi = "Skin",
                                              senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                              receivers_oi = c("Bas_mig", "Spi_mig"))

plot_oi_Skin = make_sample_lr_prod_activity_plots(multinichenet_output$prioritization_tables, prioritized_tbl_oi_Skin)
plot_oi_Skin

######################################################
# make the plot by myself (refer to the source code)
sample_data = multinichenet_output$prioritization_tables$sample_prioritization_tbl %>%
  dplyr::filter(id %in% prioritized_tbl_oi_Skin$id) %>% 
  dplyr::mutate(sender_receiver = paste(sender, receiver, sep = " --> "), 
                lr_interaction = paste(ligand, receptor, sep = " - ")) %>% 
  dplyr::arrange(receiver) %>% dplyr::group_by(receiver) %>% dplyr::arrange(sender, .by_group = TRUE)

# Check the names of facotr
fact_lev <- sample_data$sender_receiver %>% unique()
fact_lev
fact_lev <- fact_lev[c(5,7,8,6,1:4,12,14,15,13,9:11)]
# set the factor
sample_data = sample_data %>% dplyr::mutate(sender_receiver = factor(sender_receiver, levels = fact_lev))
sample_data = sample_data %>% dplyr::mutate(group = factor(group, levels = c("Skin", "Wound1", "Wound7", "Wound30")))

########################
# Sample expression plot
p1 = sample_data %>% ggplot(aes(sample, lr_interaction, color = scaled_LR_pb_prod, size = keep_sender_receiver)) + 
  geom_point() + 
  facet_grid(sender_receiver ~ group, scales = "free",
             space = "free", switch = "y") + 
  scale_x_discrete(position = "top") + 
  theme_light() + theme(axis.ticks = element_blank(), 
                        axis.title = element_blank(), 
                        axis.text.y = element_text(face = "bold.italic", size = 9), 
                        axis.text.x = element_text(size = 9, angle = 90, hjust = 0), 
                        panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(), 
                        panel.spacing.x = unit(0.4, "lines"), 
                        panel.spacing.y = unit(0.25, "lines"), 
                        strip.text.x.top = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.text.y.left = element_text(size = 9, color = "black", face = "bold", angle = 0), 
                        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) +
  labs(color = "Scaled average\nL-R expression", size = "Average fraction of\nL-R expression") + 
  scale_size_manual(values = keep_sender_receiver_values)

max_lfc = abs(sample_data$scaled_LR_pb_prod) %>% max()
custom_scale_fill = scale_color_gradientn(colours = RColorBrewer::brewer.pal(n = 7, 
  name = "RdBu") %>% rev(), values = c(0, 0.35, 0.485, 
  0.5, 0.515, 0.65, 1), limits = c(-1 * max_lfc, max_lfc))
p1 = p1 + custom_scale_fill
p1
pdf(file = "Top50_L_R_pairs_Skin.pdf", height = 10, width = 8, useDingbats = F)
p1
dev.off()
```


################################
# Plot of predicted target genes
```{r eval=FALSE}
#########
# Wound1
group_oi = "Wound1"
receiver_oi = c("Bas_mig", "Spi_mig")
contrast_tbl = tibble(contrast = c("Skin-(Wound1+Wound7+Wound30)/3","Wound1-(Skin+Wound7+Wound30)/3","Wound7-(Skin+Wound1+Wound30)/3","Wound30-(Skin+Wound1+Wound7)/3"), group = c("Skin","Wound1","Wound7","Wound30"))

prioritized_tbl_oi_grps = get_top_n_lr_pairs(multinichenet_output$prioritization_tables,
                                             top_n = 10, 
                                             groups_oi = group_oi,
                                             senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                             receivers_oi = receiver_oi
                                            )
best_upstream_ligands = prioritized_tbl_oi_grps$ligand %>% unique()
best_upstream_ligands
best_upstream_ligands <- best_upstream_ligands[c(2,1,5,3,4)];best_upstream_ligands

active_ligand_target_links_df = multinichenet_output$ligand_activities_targets_DEgenes$ligand_activities %>% 
  dplyr::ungroup() %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver == receiver_oi & group == group_oi) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ligand, target, ligand_target_weight, direction_regulation) %>% 
  dplyr::rename(weight = ligand_target_weight) %>% 
  dplyr::filter(!is.na(weight))

if (active_ligand_target_links_df$target %>% unique() %>% length() <= 2) {
  cutoff = 0
}else {
  cutoff = 0.33
}
active_ligand_target_links = nichenetr::prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, 
                                                                            ligand_target_matrix = ligand_target_matrix, 
                                                                            cutoff = cutoff)
# get the logFC of target genes
target_fc <- multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver %in% receiver_oi & group == group_oi) %>% 
  dplyr::filter(logFC >= 1)
# filter the target genes according to the logFC in wound1
active_ligand_target_links <- active_ligand_target_links[rownames(active_ligand_target_links) %in% target_fc$target, ]
  
order_ligands_ = generics::intersect(best_upstream_ligands, colnames(active_ligand_target_links)) %>% rev()
order_targets_ = active_ligand_target_links_df$target %>% unique() %>% 
  generics::intersect(rownames(active_ligand_target_links))
order_ligands = order_ligands_ %>% make.names()
order_targets = order_targets_ %>% make.names()

rownames(active_ligand_target_links) = rownames(active_ligand_target_links) %>% make.names()
colnames(active_ligand_target_links) = colnames(active_ligand_target_links) %>% make.names()
if (!is.matrix(active_ligand_target_links[order_targets, order_ligands])) {
  vis_ligand_target = active_ligand_target_links[order_targets, order_ligands] %>% matrix(ncol = 1)
  rownames(vis_ligand_target) = order_ligands
  colnames(vis_ligand_target) = order_targets
}else {
  vis_ligand_target = active_ligand_target_links[order_targets, 
    order_ligands] %>% t()
}
vis_ligand_target_df = vis_ligand_target %>% data.frame() %>% 
  tibble::rownames_to_column("ligand") %>% tidyr::gather("target", "score", -ligand) %>% tibble::as_tibble() %>%
  dplyr::mutate(ligand = factor(ligand, levels = order_ligands)) %>% 
  dplyr::inner_join(active_ligand_target_links_df %>% distinct(target, direction_regulation)) %>% 
  dplyr::mutate(target = factor(target, levels = order_targets)) %>% 
  dplyr::filter(direction_regulation == "up")

p_ligand_target_network = vis_ligand_target_df %>% 
  ggplot(aes(target, ligand, fill = score)) + 
  geom_tile(color = "whitesmoke", size = 0.5) + 
  #facet_grid(. ~ direction_regulation, scales = "free", space = "free") + 
  scale_fill_gradient2(low = "white", mid = "purple", high = "darkred", midpoint = 0.14) + 
  theme_light() + scale_x_discrete(position = "top") + 
  theme(axis.ticks = element_blank(), axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 9),
        axis.text.x = element_text(size = 9, angle = 90, hjust = 0, face = "italic"), 
        strip.text.x.top = element_text(angle = 0), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.spacing.x = unit(0.5, "lines"), 
        strip.text.x = element_text(size = 9, color = "black"), 
        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) + 
  labs(fill = "Regulatory Potential") + xlab("Predicted target genes") + 
  ylab("Prioritized ligands")

custom_scale_fill = scale_fill_gradientn(colours = c("white", RColorBrewer::brewer.pal(n = 11, name = "PiYG") %>% .[1:5] %>% rev()), values = c(0, 0.025, 0.075, 0.25, 0.4, 0.55, 1), limits = c(0, max(ligand_target_matrix)))
p_ligand_target_network = p_ligand_target_network + custom_scale_fill
p_ligand_target_network

pdf(file = "Top_ligands_predicted_TargetGene_Wound1.pdf", height = 2, width = 14, useDingbats = F)
p_ligand_target_network
dev.off()


#########
# Wound7
group_oi = "Wound7"
receiver_oi = c("Bas_mig", "Spi_mig")
contrast_tbl = tibble(contrast = c("Skin-(Wound1+Wound7+Wound30)/3","Wound1-(Skin+Wound7+Wound30)/3","Wound7-(Skin+Wound1+Wound30)/3","Wound30-(Skin+Wound1+Wound7)/3"), group = c("Skin","Wound1","Wound7","Wound30"))

prioritized_tbl_oi_grps = get_top_n_lr_pairs(multinichenet_output$prioritization_tables,
                                             top_n = 10, 
                                             groups_oi = group_oi,
                                             senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                             receivers_oi = receiver_oi
                                            )
best_upstream_ligands = prioritized_tbl_oi_grps$ligand %>% unique()
best_upstream_ligands
best_upstream_ligands <- best_upstream_ligands[c(3,2,5,1,4)];best_upstream_ligands

active_ligand_target_links_df = multinichenet_output$ligand_activities_targets_DEgenes$ligand_activities %>% 
  dplyr::ungroup() %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver == receiver_oi & group == group_oi) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ligand, target, ligand_target_weight, direction_regulation) %>% 
  dplyr::rename(weight = ligand_target_weight) %>% 
  dplyr::filter(!is.na(weight))

if (active_ligand_target_links_df$target %>% unique() %>% length() <= 2) {
  cutoff = 0
}else {
  cutoff = 0.33
}
active_ligand_target_links = nichenetr::prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, 
                                                                            ligand_target_matrix = ligand_target_matrix, 
                                                                            cutoff = cutoff)
# get the logFC of target genes
target_fc <- multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver %in% receiver_oi & group == group_oi) %>% 
  dplyr::filter(logFC >= 1)
# filter the target genes according to the logFC in wound1
active_ligand_target_links <- active_ligand_target_links[rownames(active_ligand_target_links) %in% target_fc$target, ]
  
order_ligands_ = generics::intersect(best_upstream_ligands, colnames(active_ligand_target_links)) %>% rev()
order_targets_ = active_ligand_target_links_df$target %>% unique() %>% 
  generics::intersect(rownames(active_ligand_target_links))
order_ligands = order_ligands_ %>% make.names()
order_targets = order_targets_ %>% make.names()

rownames(active_ligand_target_links) = rownames(active_ligand_target_links) %>% make.names()
colnames(active_ligand_target_links) = colnames(active_ligand_target_links) %>% make.names()
if (!is.matrix(active_ligand_target_links[order_targets, order_ligands])) {
  vis_ligand_target = active_ligand_target_links[order_targets, order_ligands] %>% matrix(ncol = 1)
  rownames(vis_ligand_target) = order_ligands
  colnames(vis_ligand_target) = order_targets
}else {
  vis_ligand_target = active_ligand_target_links[order_targets, 
    order_ligands] %>% t()
}
vis_ligand_target_df = vis_ligand_target %>% data.frame() %>% 
  tibble::rownames_to_column("ligand") %>% tidyr::gather("target", "score", -ligand) %>% tibble::as_tibble() %>%
  dplyr::mutate(ligand = factor(ligand, levels = order_ligands)) %>% 
  dplyr::inner_join(active_ligand_target_links_df %>% distinct(target, direction_regulation)) %>% 
  dplyr::mutate(target = factor(target, levels = order_targets)) %>% 
  dplyr::filter(direction_regulation == "up")

p_ligand_target_network = vis_ligand_target_df %>% 
  ggplot(aes(target, ligand, fill = score)) + 
  geom_tile(color = "whitesmoke", size = 0.5) + 
  #facet_grid(. ~ direction_regulation, scales = "free", space = "free") + 
  scale_fill_gradient2(low = "white", mid = "purple", high = "darkred", midpoint = 0.14) + 
  theme_light() + scale_x_discrete(position = "top") + 
  theme(axis.ticks = element_blank(), axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 9),
        axis.text.x = element_text(size = 9, angle = 90, hjust = 0, face = "italic"), 
        strip.text.x.top = element_text(angle = 0), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.spacing.x = unit(0.5, "lines"), 
        strip.text.x = element_text(size = 9, color = "black"), 
        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) + 
  labs(fill = "Regulatory Potential") + xlab("Predicted target genes") + 
  ylab("Prioritized ligands")

custom_scale_fill = scale_fill_gradientn(colours = c("white", RColorBrewer::brewer.pal(n = 11, name = "PiYG") %>% .[1:5] %>% rev()), values = c(0, 0.025, 0.075, 0.25, 0.4, 0.55, 1), limits = c(0, max(ligand_target_matrix)))
p_ligand_target_network = p_ligand_target_network + custom_scale_fill
p_ligand_target_network

pdf(file = "Top_ligands_predicted_TargetGene_Wound7.pdf", height = 2, width = 16, useDingbats = F)
p_ligand_target_network
dev.off()


#########
# Wound30
group_oi = "Wound30"
receiver_oi = c("Bas_mig", "Spi_mig")
contrast_tbl = tibble(contrast = c("Skin-(Wound1+Wound7+Wound30)/3","Wound1-(Skin+Wound7+Wound30)/3","Wound7-(Skin+Wound1+Wound30)/3","Wound30-(Skin+Wound1+Wound7)/3"), group = c("Skin","Wound1","Wound7","Wound30"))

prioritized_tbl_oi_grps = get_top_n_lr_pairs(multinichenet_output$prioritization_tables,
                                             top_n = 20, 
                                             groups_oi = group_oi,
                                             senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                             receivers_oi = receiver_oi
                                            )
best_upstream_ligands = prioritized_tbl_oi_grps$ligand %>% unique()
best_upstream_ligands
best_upstream_ligands <- best_upstream_ligands[c(2,1,10,9,4)];best_upstream_ligands

active_ligand_target_links_df = multinichenet_output$ligand_activities_targets_DEgenes$ligand_activities %>% 
  dplyr::ungroup() %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver == receiver_oi & group == group_oi) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ligand, target, ligand_target_weight, direction_regulation) %>% 
  dplyr::rename(weight = ligand_target_weight) %>% 
  dplyr::filter(!is.na(weight))

if (active_ligand_target_links_df$target %>% unique() %>% length() <= 2) {
  cutoff = 0
}else {
  cutoff = 0.33
}
active_ligand_target_links = nichenetr::prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, 
                                                                            ligand_target_matrix = ligand_target_matrix, 
                                                                            cutoff = cutoff)
# get the logFC of target genes
target_fc <- multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver %in% receiver_oi & group == group_oi) %>% 
  dplyr::filter(logFC >= 1)
# filter the target genes according to the logFC in wound1
active_ligand_target_links <- active_ligand_target_links[rownames(active_ligand_target_links) %in% target_fc$target, ]
  
order_ligands_ = generics::intersect(best_upstream_ligands, colnames(active_ligand_target_links)) %>% rev()
order_targets_ = active_ligand_target_links_df$target %>% unique() %>% 
  generics::intersect(rownames(active_ligand_target_links))
order_ligands = order_ligands_ %>% make.names()
order_targets = order_targets_ %>% make.names()

rownames(active_ligand_target_links) = rownames(active_ligand_target_links) %>% make.names()
colnames(active_ligand_target_links) = colnames(active_ligand_target_links) %>% make.names()
if (!is.matrix(active_ligand_target_links[order_targets, order_ligands])) {
  vis_ligand_target = active_ligand_target_links[order_targets, order_ligands] %>% matrix(ncol = 1)
  rownames(vis_ligand_target) = order_ligands
  colnames(vis_ligand_target) = order_targets
}else {
  vis_ligand_target = active_ligand_target_links[order_targets, 
    order_ligands] %>% t()
}
vis_ligand_target_df = vis_ligand_target %>% data.frame() %>% 
  tibble::rownames_to_column("ligand") %>% tidyr::gather("target", "score", -ligand) %>% tibble::as_tibble() %>%
  dplyr::mutate(ligand = factor(ligand, levels = order_ligands)) %>% 
  dplyr::inner_join(active_ligand_target_links_df %>% distinct(target, direction_regulation)) %>% 
  dplyr::mutate(target = factor(target, levels = order_targets)) %>% 
  dplyr::filter(direction_regulation == "up")

p_ligand_target_network = vis_ligand_target_df %>% 
  ggplot(aes(target, ligand, fill = score)) + 
  geom_tile(color = "whitesmoke", size = 0.5) + 
  #facet_grid(. ~ direction_regulation, scales = "free", space = "free") + 
  scale_fill_gradient2(low = "white", mid = "purple", high = "darkred", midpoint = 0.14) + 
  theme_light() + scale_x_discrete(position = "top") + 
  theme(axis.ticks = element_blank(), axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 9),
        axis.text.x = element_text(size = 9, angle = 90, hjust = 0, face = "italic"), 
        strip.text.x.top = element_text(angle = 0), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.spacing.x = unit(0.5, "lines"), 
        strip.text.x = element_text(size = 9, color = "black"), 
        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) + 
  labs(fill = "Regulatory Potential") + xlab("Predicted target genes") + 
  ylab("Prioritized ligands")

custom_scale_fill = scale_fill_gradientn(colours = c("white", RColorBrewer::brewer.pal(n = 11, name = "PiYG") %>% .[1:5] %>% rev()), values = c(0, 0.025, 0.075, 0.25, 0.4, 0.55, 1), limits = c(0, max(ligand_target_matrix)))
p_ligand_target_network = p_ligand_target_network + custom_scale_fill
p_ligand_target_network

pdf(file = "Top_ligands_predicted_TargetGene_Wound30.pdf", height = 2, width = 12, useDingbats = F)
p_ligand_target_network
dev.off()


#######
# Skin
group_oi = "Skin"
receiver_oi = c("Bas_mig", "Spi_mig")
contrast_tbl = tibble(contrast = c("Skin-(Wound1+Wound7+Wound30)/3","Wound1-(Skin+Wound7+Wound30)/3","Wound7-(Skin+Wound1+Wound30)/3","Wound30-(Skin+Wound1+Wound7)/3"), group = c("Skin","Wound1","Wound7","Wound30"))

prioritized_tbl_oi_grps = get_top_n_lr_pairs(multinichenet_output$prioritization_tables,
                                             top_n = 20, 
                                             groups_oi = group_oi,
                                             senders_oi = c("M1", "Mac_inf", "Mac_mig", "M2", "cDC1", "cDC2", "DC3", "LC"),
                                             receivers_oi = receiver_oi
                                            )
best_upstream_ligands = prioritized_tbl_oi_grps$ligand %>% unique()
best_upstream_ligands
best_upstream_ligands <- best_upstream_ligands[c(5,6,4,1,2)];best_upstream_ligands

active_ligand_target_links_df = multinichenet_output$ligand_activities_targets_DEgenes$ligand_activities %>% 
  dplyr::ungroup() %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver == receiver_oi & group == group_oi) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(ligand, target, ligand_target_weight, direction_regulation) %>% 
  dplyr::rename(weight = ligand_target_weight) %>% 
  dplyr::filter(!is.na(weight))

if (active_ligand_target_links_df$target %>% unique() %>% length() <= 2) {
  cutoff = 0
}else {
  cutoff = 0.33
}
active_ligand_target_links = nichenetr::prepare_ligand_target_visualization(ligand_target_df = active_ligand_target_links_df, 
                                                                            ligand_target_matrix = ligand_target_matrix, 
                                                                            cutoff = cutoff)
# get the logFC of target genes
target_fc <- multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% dplyr::inner_join(contrast_tbl) %>% 
  dplyr::filter(ligand %in% best_upstream_ligands & receiver %in% receiver_oi & group == group_oi) %>% 
  dplyr::filter(logFC >= 1)
# filter the target genes according to the logFC in wound1
active_ligand_target_links <- active_ligand_target_links[rownames(active_ligand_target_links) %in% target_fc$target, ]
  
order_ligands_ = generics::intersect(best_upstream_ligands, colnames(active_ligand_target_links)) %>% rev()
order_targets_ = active_ligand_target_links_df$target %>% unique() %>% 
  generics::intersect(rownames(active_ligand_target_links))
order_ligands = order_ligands_ %>% make.names()
order_targets = order_targets_ %>% make.names()

rownames(active_ligand_target_links) = rownames(active_ligand_target_links) %>% make.names()
colnames(active_ligand_target_links) = colnames(active_ligand_target_links) %>% make.names()
if (!is.matrix(active_ligand_target_links[order_targets, order_ligands])) {
  vis_ligand_target = active_ligand_target_links[order_targets, order_ligands] %>% matrix(ncol = 1)
  rownames(vis_ligand_target) = order_ligands
  colnames(vis_ligand_target) = order_targets
}else {
  vis_ligand_target = active_ligand_target_links[order_targets, 
    order_ligands] %>% t()
}
vis_ligand_target_df = vis_ligand_target %>% data.frame() %>% 
  tibble::rownames_to_column("ligand") %>% tidyr::gather("target", "score", -ligand) %>% tibble::as_tibble() %>%
  dplyr::mutate(ligand = factor(ligand, levels = order_ligands)) %>% 
  dplyr::inner_join(active_ligand_target_links_df %>% distinct(target, direction_regulation)) %>% 
  dplyr::mutate(target = factor(target, levels = order_targets)) %>% 
  dplyr::filter(direction_regulation == "up")

p_ligand_target_network = vis_ligand_target_df %>% 
  ggplot(aes(target, ligand, fill = score)) + 
  geom_tile(color = "whitesmoke", size = 0.5) + 
  #facet_grid(. ~ direction_regulation, scales = "free", space = "free") + 
  scale_fill_gradient2(low = "white", mid = "purple", high = "darkred", midpoint = 0.14) + 
  theme_light() + scale_x_discrete(position = "top") + 
  theme(axis.ticks = element_blank(), axis.title.x = element_text(size = 10), 
        axis.title.y = element_text(size = 10), axis.text.y = element_text(size = 9),
        axis.text.x = element_text(size = 9, angle = 90, hjust = 0, face = "italic"), 
        strip.text.x.top = element_text(angle = 0), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.spacing.x = unit(0.5, "lines"), 
        strip.text.x = element_text(size = 9, color = "black"), 
        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) + 
  labs(fill = "Regulatory Potential") + xlab("Predicted target genes") + 
  ylab("Prioritized ligands")

custom_scale_fill = scale_fill_gradientn(colours = c("white", RColorBrewer::brewer.pal(n = 11, name = "PiYG") %>% .[1:5] %>% rev()), values = c(0, 0.025, 0.075, 0.25, 0.4, 0.55, 1), limits = c(0, max(ligand_target_matrix)))
p_ligand_target_network = p_ligand_target_network + custom_scale_fill
p_ligand_target_network

pdf(file = "Top_ligands_predicted_TargetGene_Skin.pdf", height = 2, width = 12, useDingbats = F)
p_ligand_target_network
dev.off()
```


## 1. Load the required Ligand-target model
```{r}
organism = "human"
if(organism == "human"){
  lr_network = readRDS("new2022_db/lr_network_human_21122021.rds")
  lr_network = lr_network %>% dplyr::rename(ligand = from, receptor = to) %>% distinct(ligand, receptor) %>% mutate(ligand = make.names(ligand), receptor = make.names(receptor))
  ligand_target_matrix = readRDS("new2022_db/ligand_target_matrix_nsga2r_final.rds")
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% make.names()
} else if(organism == "mouse"){
  lr_network = readRDS("new2022_db/lr_network_mouse_21122021.rds")
  lr_network = lr_network %>% dplyr::rename(ligand = from, receptor = to) %>% distinct(ligand, receptor) %>% mutate(ligand = make.names(ligand), receptor = make.names(receptor))
  ligand_target_matrix = readRDS("new2022_db/ligand_target_matrix_nsga2r_final_mouse.rds")
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% make.names()
}

###############################################
# Plot the expression of predicted target genes

#make_ligand_activity_target_plot()
#make_DEgene_dotplot_pseudobulk()
#make_DEgene_dotplot_pseudobulk_reversed()

###############################
# Collect the ligand activity
#ligand_activity_df = multinichenet_output$prioritization_tables$ligand_activities_target_de_tbl %>% 
#  dplyr::ungroup() %>% dplyr::filter(ligand %in% order_ligands_ & receiver %in% receiver_oi) %>% 
#  dplyr::inner_join(contrast_tbl) %>% #dplyr::filter(group %in% group_oi) %>% 
#  dplyr::select(ligand, group, contrast, direction_regulation, activity) %>%
#  dplyr::distinct() %>% 
#  dplyr::mutate(ligand = factor(ligand, levels = order_ligands)) %>% 
#  dplyr::filter(direction_regulation == "up")
#p_ligand_activity_scaled = ligand_activity_df %>% ggplot(aes(group, ligand, fill = activity)) +
#  geom_tile(color = "whitesmoke") + 
#  #facet_grid(. ~ group, scales = "free", space = "free") + 
#  scale_x_discrete(position = "top") + 
#  theme_light() + 
#  theme(axis.ticks = element_blank(), 
#        axis.title.x = element_text(size = 10), 
#        axis.title.y = element_text(size = 10), 
#        axis.text.y = element_text(size = 9), 
#        axis.text.x = element_text(size = 9, angle = 90, hjust = 0), 
#        strip.text.x.top = element_text(angle = 0), 
#        panel.grid.major = element_blank(), 
#        panel.grid.minor = element_blank(), 
#        panel.spacing.x = unit(0.5, "lines"), 
#        panel.spacing.y = unit(0.5, "lines"), 
#        strip.text.x = element_text(size = 10, color = "black"), 
#        strip.text.y = element_blank(), 
#        strip.background = element_rect(color = "darkgrey", fill = "whitesmoke", size = 1.5, linetype = "solid")) + 
#  labs(fill = "Scaled Ligand\nActivity in Receiver") + 
#  ylab("Prioritized ligands") + xlab("Scaled ligand activity")
#p_ligand_activity_scaled
#max_activity = abs(ligand_activity_df$activity) %>% max(na.rm = TRUE)
#custom_scale_fill = scale_fill_gradientn(colours = c("white", 
#  RColorBrewer::brewer.pal(n = 7, name = "PuRd") %>% .[-7]), 
#  values = c(0, 0.51, 0.575, 0.625, 0.675, 0.725, 1), 
#  limits = c(-1 * max_activity, max_activity))
#p_ligand_activity_scaled = p_ligand_activity_scaled + custom_scale_fill
#p_ligand_activity_scaled
```

# Session info
```{r}
sessionInfo()
```

