---
title: "Integration of wounds and published skin data"
author: "Zhuang Liu"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 6, warning=FALSE, message=FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
#library(SeuratData)
library(SeuratDisk)
library(tidyverse)
library(patchwork)
library(harmony)
```

####################################################
# Integration of wounds and published skin data
####################################################
# 1. Prepare data as the seurat object
```{r eval=FALSE}
# process the human healthy adult skin data
Convert("/Users/zhuliu/Desktop/sc st/compareStudies/Science_MuzzLab_data/healthy_raw_lz.h5ad", 
        dest = "h5seurat", overwrite = TRUE)
healthy_skin <- LoadH5Seurat("/Users/zhuliu/Desktop/sc st/compareStudies/Science_MuzzLab_data/healthy_raw_lz.h5seurat")

healthy_skin@active.ident <- healthy_skin$sample_id
healthy_skin@misc$dendrogram_leiden <- NULL
healthy_skin@misc$rank_genes_groups <- NULL
healthy_skin@misc$Status_colors <- NULL
healthy_skin@misc$anno_colors <- NULL
healthy_skin@misc$leiden <- NULL
healthy_skin@misc$leiden_colors <- NULL

healthy_skin <- NormalizeData(healthy_skin)
colnames(healthy_skin@assays$RNA@meta.features) <- c("ensemblid", "featuretype", "ncells")
table(healthy_skin$full_clustering)

healthy_skin$full_clustering <- factor(healthy_skin$full_clustering, levels = fac_levs)
saveRDS(healthy_skin, "step4_healthy_adult_skin.rds")


# process the human fetal data
Convert("/Users/zhuliu/Desktop/sc st/compareStudies/Science_MuzzLab_data/fetal_submission_raw_lz.h5ad", 
        dest = "h5seurat", overwrite = TRUE)
sc_fetal <- LoadH5Seurat("/Users/zhuliu/Desktop/sc st/compareStudies/Science_MuzzLab_data/fetal_submission_raw_lz.h5seurat")
sc_fetal@active.ident <- sc_fetal$donor_id

sc_fetal <- NormalizeData(sc_fetal)
colnames(sc_fetal@assays$RNA@meta.features) <- c("ensemblid", "featuretype")
table(sc_fetal$anno_final)

sc_fetal$anno_final <- factor(sc_fetal$anno_final, levels = fet_fac_levs)
saveRDS(sc_fetal, "step4_fetal_skin.rds")
```

## 1. Colors for cell clusters
```{r eval=FALSE}
# human wounds data
wds_fact_lev <- c("Bas-I", "Bas-II", "Bas-prolif", "Bas-mig", 
              "Spi-I", "Spi-II", "Spi-mig", 
              "Gra-I", "HF", 
              "MEL", 
              "FB-I", "FB-II", "FB-III", "FB-prolif", 
              "Schwann", "PC-vSMC", "LE", "VE", 
              "NK-cell", "Th", "Plasma_Bcell", "Mast-cell", 
              "Mono-Mac", "cDC1", "cDC2", "DC3", "LC")
wds_ct.cols <- c("#d94701", "#fdae61", "#fd8d3c", "#fdbe85", #Basal clusters
             "#33A02C", "#72BF5A", "#B2DF8A", #Spinous clusters
             "#f768a1", "#d4b9da", #Granular, Hair follicle
             "#737373", #MEL
             "#0570b0", "#3690c0", "#92c5de", "#d1e5f0", #Fibroblast clusters
             "#c0a700", "#1a9850", "#fb9a99", "#8d4720",  # Schwann,PCvSMC,LE,VE
             "#35978f", "#41b6c4", "#80cdc1","#df65b0", #"NK-cell", "Th", "Plasma_Bcell", "Mast-cell", 
             "#dd3497", "#807dba","#6a3d9a","#9e9ac8", "#b15928" #"Mono-Mac", "cDC1", "cDC2", "DC3", "LC"
)
# add the color names using new cell types
names(wds_ct.cols) <- wds_fact_lev


# human adult skin data
fac_levs <- c("Undifferentiated_KC", "Differentiated_KC", "Melanocyte",
              "Schwann_1", "Schwann_2", 
              "F1", "F2", "F3", 
              "Pericyte_1", "Pericyte_2",
              "VE1", "VE2", "VE3", "LE1", "LE2",
              "ILC1_3", "ILC1_NK", "NK", "ILC2", "Tc", "Th", "Treg",
              "Mast_cell", "Plasma",
              "Macro_1", "Macro_2", "Inf_mac",
              "DC1", "DC2", "LC", "Mono_mac", "MigDC", "migLC", "moDC")
ct.cols <- c("#B5B6DB", "#166E8A", "#D5DEA0",
             "#A6559B", "#3E64A2", 
             "#A4D7E2", "#6BA0D5", "#3A64AD",
             "#E4DCC0", "#F19570", 
             "#EAD6E8", "#EF93AA", "#E23725", "#0D783D", "#7FBD70",
             "#CEDFEF", "#4DA1D1", "#1B4179", "#86AB3E", "#A0CA7A", "#90398F", "#A67FBA", 
             "#C39371", "#F2DDEB", 
             "#D43A6B", "#B97781", "#194791",
             "#DF7A90", "#E49CC4", "#BADFE9", "#852E8A", "#EFC1DA", "#7D85BA", "#4AB6AF")
names(ct.cols) <- fac_levs


# human fetal data
fet_fac_levs=c("A_fs_KC", "B_fs_Melanocyte", "C_fs_Schwann", 
               "D_fs_FB", "E_fs_LE", "F_fs_VE", "N_fs_pericyte", 
               "G_fs_Mast", "H_fs_NK", "I_fs_ILC", "J_fs_LC",
               "K_fs_DC1", "L_fs_DC2", "M_fs_Macro")

fet_ct.cols=c("#B6B7DC", "#D2DA8E", "#974794", 
              "#98D2E0", "#1C6835", "#EB718A", "#668A5D",
              "#C39371", "#31499A", "#C5D779", "#B6B7DC",
              "#DAADC0", "#8C87A7", "#305092")
names(fet_ct.cols) <- fet_fac_levs
```


# 2. Integrate the healthy adult skin data with wounds data
```{r eval=FALSE}
# healthy adult skin integration using the donor as the batch effect, 
# while the wounds data using each sample as the batch effect
healthy_skin <- readRDS("step4_healthy_adult_skin.rds")
DimPlot(healthy_skin, group.by = "full_clustering", label = F, cols = ct.cols, raster=TRUE) + ggtitle("")


# integrate based on sample names. For wounds data, use sample ID, 
# while healthy adult data, use each donor as mentioned in the paper
healthy_skin$Project="HealthyAdult"
healthy_skin$Sample=healthy_skin$donor_id
healthy_skin$CellType=healthy_skin$full_clustering

# process the human wounds data (reduce the object size)
# load the human wounds data
wounds <- readRDS("/Users/zhuliu/Desktop/sc st/plotting scripts/Figure 1/allcombined_wounds_newAnnotation.rds")
wounds@reductions$umap_def <- NULL
# only keep 40 PCs of pca
wounds@reductions$pca@cell.embeddings = Embeddings(wounds@reductions$pca)[,1:40]
wounds@reductions$pca@feature.loadings = wounds@reductions$pca@feature.loadings[,1:40]
wounds@reductions$pca@stdev = wounds@reductions$pca@stdev[1:40]

# only keep 40 PCs of harmony
wounds@reductions$harmony@cell.embeddings = Embeddings(wounds@reductions$harmony)[,1:40]
wounds@reductions$harmony@feature.loadings = wounds@reductions$harmony@feature.loadings[,1:40]
# remove the feature.loadings.projected in the harmony slot, since it is duplicated as feature.loadings
wounds@reductions$harmony@feature.loadings.projected = wounds@reductions$pca@feature.loadings.projected
wounds@reductions$harmony@stdev = wounds@reductions$harmony@stdev[1:40]

wounds$Doublet=NULL;wounds$percent.ribo=NULL;wounds$percent.hb=NULL;wounds$percent.malat1=NULL;wounds$Phase=NULL;wounds$nCount_SCT=NULL;wounds$nFeature_SCT=NULL;wounds$SCT_snn_res.0.5=NULL;wounds$seurat_clusters=NULL;wounds$SCT_snn_res.0.8=NULL;wounds$doublet_scores=NULL;wounds$CellTypes=NULL;wounds$nCount_RNA=NULL;wounds$nFeature_RNA=NULL

DefaultAssay(wounds) <- "SCT"
DimPlot(wounds, group.by = "newCellTypes", label = F, cols = wds_ct.cols, raster=TRUE) + ggtitle("")


# check the overlapped genes and keep the overlapped genes
overgene <- intersect(rownames(healthy_skin), rownames(wounds))

healthy_skin <- healthy_skin[overgene, ]
wounds <- wounds[overgene, ]
```


# 3. Mapping using the integrated reference (wounds data)
```{r eval=FALSE}
options(future.globals.maxSize = 100000 * 1024^2) 
healthy_skin = DietSeurat(healthy_skin, assays = "RNA")
all.health = SplitObject(healthy_skin, split.by = "Sample")
all.health = lapply(all.health, SCTransform, assay = "RNA", variable.features.n = 4000,
    verbose = F, method = "glmGamPoi")

vg = SelectIntegrationFeatures(all.health, verbose = F, nfeatures = 4000)
# get all genes in SCT assay of the objects
genes.all = lapply(all.health, function(x) rownames(x@assays$SCT@data))
t = table(unlist(genes.all))

expr.all = names(t)[t == length(all.health)]
vg = intersect(vg, expr.all)
length(vg)

all.health = PrepSCTIntegration(all.health, anchor.features = vg, verbose = F)

healthdata.merged <- merge(all.health[[1]], y = c(all.health[2:length(all.health)]), merge.data = TRUE)
healthdata.merged@active.assay = "SCT"
VariableFeatures(healthdata.merged) <- vg

rm(all.health, healthy_skin)
gc(verbose = F)
```


# 4. Run harmony
```{r eval=FALSE}
wounds@assays$SCT@SCTModel.list <- wounds@assays$SCT@SCTModel.list[1]
health.anchors <- FindTransferAnchors(reference = wounds, 
                                      query = healthdata.merged, 
                                      normalization.method = "SCT", 
                                      reference.assay = "SCT",
                                      reference.reduction = "harmony", 
                                      dims = 1:40, npcs = 40)
predictions <- TransferData(anchorset = health.anchors, 
                            refdata = wounds$newCellTypes)
healthdata.merged <- AddMetaData(healthdata.merged, metadata = predictions)

saveRDS(healthdata.merged, file = "wounds_transfer_health.rds")
```


```{r}
#inte_transfer <- readRDS("step4wounds_transfer_health.rds")
#metadata <- inte_transfer@meta.data %>% rownames_to_column(var = "barcode")
#data.table::fwrite(metadata, "step4wounds_transfer_health_metadata.txt")
library(RColorBrewer)
library(viridis)
library(pheatmap)

metadata <- data.table::fread("step4wounds_transfer_health_metadata.txt")
table(metadata$predicted.id)

selcolums <- colnames(metadata %>% dplyr::select(18:44))
selcolums <- gsub("prediction.score.", "", selcolums)
selcolums <- gsub("\\.", "_", selcolums)
corre <- metadata %>% dplyr::select(12, 18:44) %>% group_by(CellType) %>%
  mutate(Bas_I = median(prediction.score.Bas.I)) %>% 
  mutate(Bas_II = median(prediction.score.Bas.II)) %>% 
  mutate(Bas_prolif = median(prediction.score.Bas.prolif)) %>% 
  mutate(Bas_mig = median(prediction.score.Bas.mig)) %>% 
  mutate(Spi_I = median(prediction.score.Spi.I)) %>% 
  mutate(Spi_II = median(prediction.score.Spi.II)) %>% 
  mutate(Spi_mig = median(prediction.score.Spi.mig)) %>% 
  mutate(Gra_I = median(prediction.score.Gra.I)) %>% 
  mutate(HF = median(prediction.score.HF)) %>% 
  mutate(MEL = median(prediction.score.MEL)) %>% 
  mutate(FB_I = median(prediction.score.FB.I)) %>% 
  mutate(FB_II = median(prediction.score.FB.II)) %>% 
  mutate(FB_III = median(prediction.score.FB.III)) %>% 
  mutate(FB_prolif = median(prediction.score.FB.prolif)) %>% 
  mutate(Schwann = median(prediction.score.Schwann)) %>% 
  mutate(PC_vSMC = median(prediction.score.PC.vSMC)) %>% 
  mutate(LE = median(prediction.score.LE)) %>% 
  mutate(VE = median(prediction.score.VE)) %>% 
  mutate(NK_cell = median(prediction.score.NK.cell)) %>% 
  mutate(Th = median(prediction.score.Th)) %>% 
  mutate(Plasma_Bcell = median(prediction.score.Plasma_Bcell)) %>% 
  mutate(Mast_cell = median(prediction.score.Mast.cell)) %>% 
  mutate(Mono_Mac = median(prediction.score.Mono.Mac)) %>% 
  mutate(cDC1 = median(prediction.score.cDC1)) %>% 
  mutate(cDC2 = median(prediction.score.cDC2)) %>% 
  mutate(DC3 = median(prediction.score.DC3)) %>% 
  mutate(LC = median(prediction.score.LC)) %>% ungroup() %>% dplyr::select(1, 29:55) %>% distinct()

fac_levs <- c("Undifferentiated_KC", "Differentiated_KC", "Melanocyte",
              "Schwann_1", "Schwann_2", 
              "F1", "F2", "F3", 
              "Pericyte_1", "Pericyte_2",
              "VE1", "VE2", "VE3", "LE1", "LE2",
              "ILC1_3", "ILC1_NK", "NK", "ILC2", "Tc", "Th", "Treg",
              "Mast_cell", "Plasma",
              "Macro_1", "Macro_2", "Inf_mac",
              "DC1", "DC2", "LC", "Mono_mac", "MigDC", "migLC", "moDC")
a_ord <- match(fac_levs, corre$CellType)
corre <- corre[c(a_ord),]
htmap <- corre %>% dplyr::select(-3) %>% column_to_rownames(var = "CellType")

pheatmap::pheatmap(htmap, cluster_rows = F, cluster_cols = F, color = inferno(10))

```


# SessionInfo
```{r}
sessionInfo()
```

