---
title: "scVelo preparation"
author: "Zhuang Liu"
date: "02/12/2021 Updated: `r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 8, warning=FALSE, message=FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(magrittr)
```

#########################################################
# Step -1: Convert data from Seurat to Python / anndata
#########################################################
## All conditions
```{r}
hswound.krt.com <- readRDS("./allNew_subcluster_keratins_220203.rds")
hswound.krt.com <- readRDS("./p_try_KRT6A+_wound_cells.rds")
compseudo <- readRDS("allNew_subcluster_keratins_220207_eachCondition_comPseudotimes.rds")

mt <- hswound.krt.com@meta.data %>% rownames_to_column(var = "CellID")
mt <- mt %>% left_join(., compseudo, by=c("CellID" = "CellID")) %>% column_to_rownames(var = "CellID")

hswound.krt.com <- AddMetaData(hswound.krt.com, metadata = mt)
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$seurat_clusters <- as.character(hswound.krt.com$seurat_clusters)
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "CellTypes") + NoAxes() + NoLegend() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@meta.data, file='p_try_KRT6A_wound_cells_scVelo/metadata_w.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts.mtx')
writeMM(counts_matrix, file='p_try_KRT6A_wound_cells_scVelo/counts_w.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='p_try_KRT6A_wound_cells_scVelo/pca_w.csv', quote=F, row.names=F)

write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='p_try_KRT6A_wound_cells_scVelo/harmony_w.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names.csv',
  quote=F,row.names=F,col.names=F)
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='p_try_KRT6A_wound_cells_scVelo/gene_names_w.csv',
  quote=F,row.names=F,col.names=F)
```


## Only Skin
```{r}
rm(list = ls());gc()
hswound.krt.com <- readRDS("./allNew_subcluster_keratinocytes_dels_skin.rds")
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
str(hswound.krt.com@meta.data)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$seurat_clusters <- paste0("cl", as.character(hswound.krt.com$seurat_clusters))
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters") + NoAxes() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata_skin.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts_skin.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca_skin.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony_skin.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names_skin.csv',
  quote=F,row.names=F,col.names=F)
```

## Only wound1
```{r}
rm(list = ls());gc()
hswound.krt.com <- readRDS("./allNew_subcluster_keratinocytes_dels_wound1.rds")
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
str(hswound.krt.com@meta.data)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$seurat_clusters <- paste0("cl", as.character(hswound.krt.com$seurat_clusters))
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters") + NoAxes() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata_wound1.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts_wound1.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca_wound1.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony_wound1.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names_wound1.csv',
  quote=F,row.names=F,col.names=F)
```


## Only Wound7
```{r}
rm(list = ls());gc()
hswound.krt.com <- readRDS("./allNew_subcluster_keratinocytes_dels_wound7.rds")
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
str(hswound.krt.com@meta.data)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$SCT_snn_res.1.4 <- as.character(hswound.krt.com$SCT_snn_res.1.4)
hswound.krt.com$seurat_clusters <- paste0("cl", as.character(hswound.krt.com$seurat_clusters))
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters") + NoAxes() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata_wound7.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts_wound7.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca_wound7.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony_wound7.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names_wound7.csv',
  quote=F,row.names=F,col.names=F)
```


## Only Wound30
```{r}
rm(list = ls());gc()
hswound.krt.com <- readRDS("./allNew_subcluster_keratinocytes_dels_wound30.rds")
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
str(hswound.krt.com@meta.data)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$SCT_snn_res.1.4 <- as.character(hswound.krt.com$SCT_snn_res.1.4)
hswound.krt.com$SCT_snn_res.1.2 <- as.character(hswound.krt.com$SCT_snn_res.1.2)
hswound.krt.com$seurat_clusters <- paste0("cl", as.character(hswound.krt.com$seurat_clusters))
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters") + NoAxes() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata_wound30.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts_wound30.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca_wound30.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony_wound30.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names_wound30.csv',
  quote=F,row.names=F,col.names=F)
```


## All Wounds
```{r}
rm(list = ls());gc()
hswound.krt.com <- readRDS("./allNew_subcluster_keratinocytes_dels_wounds.rds")
DefaultAssay(hswound.krt.com) <- "RNA"
# save metadata table: (first change the data type of cell clusters)
str(hswound.krt.com@meta.data)
hswound.krt.com$nCount_SCT <- NULL
hswound.krt.com$nFeature_SCT <- NULL
hswound.krt.com$fil <- NULL
hswound.krt.com$orig.ident <- as.character(hswound.krt.com$orig.ident)
hswound.krt.com$Age <- as.character(hswound.krt.com$Age)
hswound.krt.com$Condition <- as.character(hswound.krt.com$Condition)
hswound.krt.com$SCT_snn_res.0.5 <- as.character(hswound.krt.com$SCT_snn_res.0.5)
hswound.krt.com$SCT_snn_res.0.8 <- as.character(hswound.krt.com$SCT_snn_res.0.8)
hswound.krt.com$SCT_snn_res.1 <- as.character(hswound.krt.com$SCT_snn_res.1)
hswound.krt.com$SCT_snn_res.1.4 <- as.character(hswound.krt.com$SCT_snn_res.1.4)
hswound.krt.com$SCT_snn_res.1.2 <- as.character(hswound.krt.com$SCT_snn_res.1.2)
hswound.krt.com$seurat_clusters <- paste0("cl", as.character(hswound.krt.com$SCT_snn_res.1))
str(hswound.krt.com@meta.data)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters") + NoAxes() + ggtitle("Cell Clusters")

hswound.krt.com$barcode <- as.character(colnames(hswound.krt.com))
hswound.krt.com$UMAP_1 <- hswound.krt.com@reductions$umap@cell.embeddings[,1]
hswound.krt.com$UMAP_2 <- hswound.krt.com@reductions$umap@cell.embeddings[,2]
write.csv(hswound.krt.com@meta.data, file='allNew_zs3_scVelo_preparation/metadata_wounds.csv', quote=F, row.names=F)

# write expression counts matrix
library(Matrix)
counts_matrix <- GetAssayData(hswound.krt.com, assay='RNA', slot='counts')
writeMM(counts_matrix, file='allNew_zs3_scVelo_preparation/counts_wounds.mtx')

# write dimesnionality reduction matrix, pca and harmony
write.csv(hswound.krt.com@reductions$pca@cell.embeddings, file='allNew_zs3_scVelo_preparation/pca_wounds.csv', quote=F, row.names=F)
write.csv(hswound.krt.com@reductions$harmony@cell.embeddings, file='allNew_zs3_scVelo_preparation/harmony_wounds.csv', quote=F, row.names=F)

# write gene names
write.table(
  data.frame('gene'=rownames(counts_matrix)),file='allNew_zs3_scVelo_preparation/gene_names_wounds.csv',
  quote=F,row.names=F,col.names=F)
```

# SessionInfo
```{r}
sessionInfo()
```
