---
title: "Test deconv with SCDC"
author: "Åsa Björklund"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    self_contained: true
    highlight: tango
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    fig_caption: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=12,tidy=TRUE)
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
```

Test SCDC using Secction Donor3_Wound7

Following tutorial in:
https://github.com/dmcable/RCTD/blob/master/vignettes/spatial-transcriptomics.Rmd

## Load

### Load packages

```{r packages}


library(SCDC)
library(Matrix)
library(Biobase)
```


```{r}
input_dir = "../../../deconv/inputs/"
output_dir = "../../../deconv/results/scdc/"
dir.create(output_dir, showWarnings = F)
    
sample = "Donor3_Wound7"

outdir = file.path(output_dir,sample)
dir.create(outdir, showWarnings = F)

indir = file.path(input_dir,"st_data",sample)   
    

raw_path = readLines(file.path(indir,"rawdata_path.csv"))
print(raw_path)   

barcodes = read.csv(file.path(indir, "barcodes.csv"), header = F)
```


Load gene list

```{r}
gene.file = "../../../deconv/inputs/sc_data/degs_fc0.5_pval0.01.txt"

d.genes = read.csv(gene.file, header = F)
d.genes = d.genes[,1]

```


Load SC data

```{r}
scC = readMM(file.path(input_dir, "sc_data", "s1_subsampled_counts.mtx"))
# convert to dgCMatrix
scC = scC*1

genes = read.table(file.path(input_dir, "sc_data", "s1_subsampled_features.csv"), header = F)
rownames(scC) = genes[,1]

scMeta = read.csv(file.path(input_dir, "sc_data", "s1_subsampled_meta.csv"))
colnames(scC) = scMeta$barcode
rownames(scMeta) = scMeta$barcode
```

Create the SC object

```{r}
sc.data = ExpressionSet(assayData=as.matrix(scC[d.genes,]),
                         phenoData =  AnnotatedDataFrame(scMeta))

rm(scC)
g = gc(verbose = F)
```


Load ST data

```{r}
stC = readMM(file.path(indir,"counts.mtx"))
stC = stC*1
# read gene names
genes = read.csv(file.path(input_dir, "st_data", "st_features.csv"), header = F)
rownames(stC) = genes[,1]

coord = read.csv(file.path(indir,"coordinates.csv"))
colnames(stC) = coord$X

```

Create ST object

```{r}
nUMI = colSums(stC)

cc = data.frame(xcoord=coord$imagerow, ycoord=coord$imagecol)
rownames(cc) = coord$X

st.data = ExpressionSet(assayData=as.matrix(stC[d.genes,]),
                         phenoData =  AnnotatedDataFrame(cc))
```





## Run SCDC


```{r}
deconvolution_crc <- SCDC_prop(bulk.eset = st.data,
                       sc.eset = sc.data,
                       ct.varname = "cluster",
                       ct.sub = as.character(unique(scMeta$cluster)) )


```


```{r}
write.csv(deconvolution_crc$prop.est.mvw, quote = F, file=file.path(outdir, "scdc_prop.est.mvw.csv"))

saveRDS(deconvolution_crc, file=file.path(outdir, "scdc_prop_obj.rds"))
```

## With 


### Session info

```{r}
sessionInfo()
```
