---
title: "Sub-clustering of Keratinocytes"
author: "Zhuang Liu"
date: "30/11/2021 Updated: `r Sys.Date()`"
output:
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width = 12, warning = FALSE, message = FALSE)
```

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(SeuratObject)
library(SeuratDisk)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(harmony)
```


```{r}
hswound.krt.com <- readRDS("allNew_subcluster_keratins_220203.rds")
mtdf <- read_csv("p_try_KRT6A_wound_cells_GaussianSelection_metadata.csv")
identical(colnames(hswound.krt.com), mtdf$barcode)

hswound.krt.com$KRT6A_class <- mtdf$KRT6A_class
hswound.krt.com$KRT6B_class <- mtdf$KRT6B_class
hswound.krt.com$KRT6C_class <- mtdf$KRT6C_class
hswound.krt.com$KRT16_class <- mtdf$KRT16_class
hswound.krt.com$KRT17_class <- mtdf$KRT17_class

(DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = F, group.by = "KRT6A_class", split.by = "Condition",
        cols = c("#D8B264", "#D8B264", "#35978f"), ncol = 2) + NoAxes() + ggtitle(""))
pdf("Fig3_UMAP_kera_skinwounds_supple.pdf", useDingbats = F, width = 11, height = 7)
dev.off()

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = F, group.by = "KRT17_class", split.by = "Condition") + NoAxes() + ggtitle("")

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = F, group.by = "Condition", split.by = "KRT17_class") + NoAxes() + ggtitle("")

table(hswound.krt.com$CellTypes, hswound.krt.com$KRT6A_class)
table(hswound.krt.com$CellTypes, hswound.krt.com$KRT6B_class)
table(hswound.krt.com$CellTypes, hswound.krt.com$KRT6C_class)
table(hswound.krt.com$CellTypes, hswound.krt.com$KRT16_class)
table(hswound.krt.com$CellTypes, hswound.krt.com$KRT17_class)

table(hswound.krt.com$Condition, hswound.krt.com$KRT6A_class)
table(hswound.krt.com$Condition, hswound.krt.com$KRT6B_class)
table(hswound.krt.com$Condition, hswound.krt.com$KRT6C_class)
table(hswound.krt.com$Condition, hswound.krt.com$KRT16_class)
table(hswound.krt.com$Condition, hswound.krt.com$KRT17_class)

fac_levs <- c("Bas_I", "Bas_II", "Bas_III", 
              "Spi_I", "Spi_II", "Spi_III","Spi_IV", "Spi_V",
              "Gra_I")
```

## Rerun the SCT and clustering (all Conditions)
```{r}
table(hswound.krt.com$KRT6A_class)
wound.cells <- subset(hswound.krt.com, subset = KRT6A_class == "KRT6A+")
wound.cells@meta.data <- droplevels(wound.cells@meta.data)
highCells1 <- mtdf %>% filter(KRT6A_class == "KRT6A+") %>% pull(barcode)
highCells2 <- mtdf %>% filter(KRT6A_class != "KRT6A+") %>% pull(barcode)
highCells2 <- highCells2[-1]
(DimPlot(object = hswound.krt.com, 
         cells.highlight = list(Wounds = highCells, Skin = highCells2),
         cols.highlight = c("#35978f", "#D8B264"),
         sizes.highlight = 0.2,
         reduction = "umap") + NoAxes() + ggtitle(""))
pdf("Fig3_UMAP_kera_skinwounds.pdf", useDingbats = F, width = 6, height = 4)
dev.off()

DefaultAssay(wound.cells) <- "RNA"
wound.cells <- DietSeurat(wound.cells, counts = TRUE, data = TRUE, scale.data = FALSE,
                    assays = "RNA", dimreducs = NULL)
#Remove unneeded columns
wound.cells@active.ident <- wound.cells$orig.ident
wound.cells$SCT_snn_res.0.5 <- NULL
wound.cells$SCT_snn_res.0.8 <- NULL
wound.cells$SCT_snn_res.1 <- NULL
wound.cells$seurat_clusters <- NULL
wound.cells$nCount_SCT <- NULL
wound.cells$nFeature_SCT <- NULL

table(wound.cells$Condition)
table(wound.cells$orig.ident)

hswound.list <- SplitObject(wound.cells, split.by = "orig.ident")
rm(wound.cells);invisible(gc())
hswound.list <- lapply(X = hswound.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- CellCycleScoring(object = x, g2m.features = cc.genes$g2m.genes, s.features = cc.genes$s.genes, set.ident = FALSE)
  x$CC.Difference <- x$S.Score - x$G2M.Score
  x <- SCTransform(x, vars.to.regress = c("percent.mt", "CC.Difference"), variable.features.n = 2000, verbose = FALSE, return.only.var.genes = TRUE, method = "glmGamPoi")
})

features.all <- SelectIntegrationFeatures(object.list = hswound.list, nfeatures = 2000) # nfeature = 1500 for wound cells, nfeature = 2000 for healthy cells 
rn <- lapply(hswound.list, rownames) 
nE <- colSums(Reduce(rbind, lapply(rn, function(x) features.all %in% x))) 
features.all <- features.all[nE == length(hswound.list)]

eachvg <- list(
  PWH26D0=VariableFeatures(hswound.list$PWH26D0), 
  PWH26D1=VariableFeatures(hswound.list$PWH26D1),
  PWH26D30=VariableFeatures(hswound.list$PWH26D30),
  PWH26D7=VariableFeatures(hswound.list$PWH26D7),
  PWH27D0=VariableFeatures(hswound.list$PWH27D0),
  PWH27D1=VariableFeatures(hswound.list$PWH27D1),
  PWH27D30=VariableFeatures(hswound.list$PWH27D30),
  PWH27D7=VariableFeatures(hswound.list$PWH27D7),
  PWH28D0=VariableFeatures(hswound.list$PWH28D0),
  PWH28D1=VariableFeatures(hswound.list$PWH28D1),
  PWH28D30=VariableFeatures(hswound.list$PWH28D30),
  PWH28D7=VariableFeatures(hswound.list$PWH28D7),
  krtallvg=features.all)
source("../Functions/overlap_phyper2.R")
overlap_phyper2(eachvg, eachvg)

####----Prepare the integration----####
hswound.list <- PrepSCTIntegration(object.list = hswound.list, anchor.features = features.all)

hswound.krt.com <- merge(hswound.list[[1]], 
                         y = hswound.list[2:length(hswound.list)],
                         project = "woundcells",
                         merge.data = TRUE)

VariableFeatures(hswound.krt.com) <- features.all
hswound.krt.com <- RunPCA(object = hswound.krt.com, assay = "SCT", npcs = 50, features = VariableFeatures(hswound.krt.com))
ElbowPlot(hswound.krt.com, ndims = 50, reduction = "pca")

#rm(hswound.list);invisible(gc())

hswound.krt.com <- RunHarmony(object = hswound.krt.com,
                                    assay.use = "SCT",
                                    reduction = "pca",
                                    dims.use = 1:20, #dims.use = 1:20 for wound cells, dims.use = 1:30 for healthy cells
                                    group.by.vars = "orig.ident",
                                    plot_convergence = TRUE)


hswound.krt.com$orig.ident <- factor(x = hswound.krt.com$orig.ident, levels =
                                            c("PWH26D0", "PWH26D1", "PWH26D7","PWH26D30",
                                              "PWH27D0", "PWH27D1", "PWH27D7","PWH27D30",
                                              "PWH28D0", "PWH28D1", "PWH28D7","PWH28D30"))
hswound.krt.com$Condition <- factor(x = hswound.krt.com$Condition, levels =
                                            c("Skin", "Wound1", "Wound7","Wound30"))

#rn pca, umap, clustering
hswound.krt.com <- FindNeighbors(object = hswound.krt.com, assay = "SCT", reduction = "harmony", dims = 1:20, k.param = 40)
#hswound.krt.com <- FindNeighbors(object = hswound.krt.com, assay = "SCT", reduction = "harmony", dims = 1:30, k.param = 60)
hswound.krt.com <- FindClusters(object = hswound.krt.com, resolution = 0.8)
hswound.krt.com <- FindClusters(object = hswound.krt.com, resolution = 0.5)
hswound.krt.com <- FindClusters(object = hswound.krt.com, resolution = 1.0)

hswound.krt.com <- RunUMAP(object = hswound.krt.com, assay = "SCT", reduction = "harmony", dims = 1:20, n.neighbors = 40, min.dist = 0.2, n.epochs = 500, spread = 1.5, learning.rate = 1)
hswound.krt.com <- RunUMAP(object = hswound.krt.com, assay = "SCT", reduction = "harmony", dims = 1:20, n.neighbors = 40)

#hswound.krt.com <- RunUMAP(object = hswound.krt.com, assay = "SCT", reduction = "harmony", dims = 1:30, n.neighbors = 60, min.dist = 0.3, n.epochs = 500, spread = 1, learning.rate = 1)

#hswound.krt.com <- readRDS(file = "allNew_subcluster_keratinocytes_dels.rds")

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "SCT_snn_res.0.5", label.size = 4.5) + NoAxes()
DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "SCT_snn_res.0.8", label.size = 4.5) + NoAxes()
DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "SCT_snn_res.1", label.size = 4.5) + NoAxes()

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "CellTypes", label.size = 5) + NoAxes() + ggtitle("")


DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "SCT_snn_res.0.8", label.size = 4.5, split.by = "Condition") + NoAxes()

####----Change to RNA assay to prepare the DE analysis----####
DefaultAssay(hswound.krt.com) <- "RNA" #DE for all genes instead of only using variable gene
hswound.krt.com <- NormalizeData(hswound.krt.com, verbose = TRUE,  normalization.method = "LogNormalize", scale.factor = 10000)

#saveRDS(hswound.krt.com, file = "p_try_KRT6A+_wound_cells.rds")
#saveRDS(hswound.krt.com, file = "p_try_KRT6A-dim_healthy_cells.rds")
```

### 2.2.1 marker genes
```{r eval=FALSE}
rm(list = ls());invisible(gc())
#hswound.krt.com <- readRDS("p_try_KRT6A+_wound_cells.rds")
hswound.krt.com <- readRDS("p_try_KRT6A-dim_healthy_cells.rds")
genes <- VariableFeatures(hswound.krt.com) %>% as.data.frame()
write_csv2(genes, "variablegene_healthycell.csv")

DefaultAssay(hswound.krt.com) <- "RNA" 
library(future)
plan("multisession", workers = 4)
options(future.globals.maxSize = 15000 * 1024^2)

#Idents(hswound.krt.com) <- "CellTypes" # marker genes with annotated clusters 
Idents(hswound.krt.com) <- "SCT_snn_res.0.5" #marker genes with cluster number
table(hswound.krt.com$SCT_snn_res.0.5)
####----FindAllMarkers for all clusters----####
library(MAST)
markers <- FindAllMarkers(
  hswound.krt.com,
  only.pos = TRUE,
  min.pct = 0.25,  #min.pct = 0.5, logfc.threshold = 0.5,
  logfc.threshold = 0.25,
  test.use = "MAST") #MAST has good FDR control and is faster than DESeq2, default test is wilcox

####----add the gene description to the cluster marker genes----####
annot <- readRDS("../Functions/humanAnnotation.rds")
####----add the info and reorder the columns----####
markers_f <- markers %>% left_join(., annot, by=c("gene" = "external_gene_name")) %>% 
  dplyr::select(6, 7, 2:4, 1, 5, everything()) %>% arrange(cluster, desc(avg_log2FC))
#marker genes with cluster number
#data.table::fwrite(markers_f, file="./p_try_KRT6A_wound_cells_scVelo/p_try_KRT6A+_wound_cells_markergenes.txt", sep="\t") ## marker genes with annotated clusters 
data.table::fwrite(markers_f, file="./p_try_KRT6A_wound_cells_scVelo/p_try_KRT6A-dim_healthy_cells_markergenes.txt", sep="\t")
```

## plotting
```{r}
genes <-  c("KRT5","KRT10","KRT16", "KRT17", "KRT6A", "KRT6B", "KRT6C", "MKI67",
            "KRT15", "POSTN", "MMP1", "MMP3", "KRTDAP", "KRT2", "IVL", "FLG")
genes <-  c("AREG")

p3 <- FeaturePlot(
  hswound.krt.com,
  features = genes,
  cols = c("grey", "red"), min.cutoff = 0.001, combine = FALSE)
p2_list <- lapply(p3, function(x) {x + NoAxes() + theme(text = element_text(size = 10))})
wrap_plots(p2_list, ncol = 8)

DimPlot(object = hswound.krt.com, 
        reduction = "umap", 
        label = TRUE, 
        cells.highlight = colnames(subset(hswound.krt.com, subset = CellTypes == c("Gra_III"))),
        group.by = "CellTypes", label.size = 5) + NoAxes() + NoLegend() + ggtitle("")
```



```{r}
hswound.krt.com <- readRDS("p_try_KRT6A+_wound_cells.rds")
table(hswound.krt.com$CellTypes)
table(hswound.krt.com$SCT_snn_res.0.5)

hswound.krt.com <- readRDS("p_try_KRT6A-dim_healthy_cells.rds")
table(hswound.krt.com$CellTypes)
table(hswound.krt.com$SCT_snn_res.0.5)
```

# SessionInfo
```{r}
sessionInfo()
```
