name: R_rctd
channels:
 - conda-forge
 - anaconda
 - bioconda
 - defaults
 - r
dependencies:
 - r-base=4.0.3
 - rstudio
 - r-biocmanager
 - r-remotes
 - compilers
 - r-devtools
 - r-cowplot
 - r-ggplot2
 - r-ggraph
 - r-matrix
 - r-doparallel
 - r-reshape2
 - r-reticulate
 - r-dplyr
 - r-tibble
 - r-pals
 - r-foreach
 - r-hdf5r
 - hdf5
 - r-quadprog
 - r-scatterpie
 - r-knitr
 - r-rmarkdown
 - r-readr
 - r-tibble
 - r-pheatmap
 - r-optparse
 - wget
 - r-checkmate
 - r-pkgmaker
 - bioconductor-annotationdbi
 - r-nnls
 - r-reshape
 - r-l1pack
 - bioconductor-biobase
 

# remotes::install_github("dmcable/RCTD", ref = "master", build_vignettes = FALSE, dependencies = FALSE)


#Downloading GitHub repo dmcable/RCTD@HEAD
#Error in utils::download.file(url, path, method = method, quiet = quiet,  :
#  download from 'https://api.github.com/repos/dmcable/RCTD/tarball/HEAD' failed, need to add ref = "master"

# Also add SCDC to same env.
# Recommends xbioc from:
# remotes::install_github("renozao/xbioc", dependencies=FALSE)
# devtools::install_github("meichendong/SCDC", dependencies=FALSE)
