---
title: "Stereoscope prediction summary"
author: "Zhuang Liu"
date: "Updated: `r Sys.Date()`"
output: 
  html_document:
    toc: true #add a table of contents (TOC)
    toc_depth: 3 #headers' level in the toc
    toc_float: true #toc visible even when scrolled
    theme: lumen
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align='center', fig.width=12, fig.height = 7, warning=FALSE, message=FALSE)
```

## Load packages

```{r packages}
suppressPackageStartupMessages(require(Matrix))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(Seurat))
suppressPackageStartupMessages(require(ggplot2))
suppressPackageStartupMessages(require(gridExtra))
```

```{r}
cl.colors = c("#e6194B", "#3cb44b", "#ffe119", "#4363d8", "#f58231", "#911eb4", "#42d4f4",
    "#f032e6", "#bfef45", "#fabed4", "#469990", "#dcbeff", "#9A6324", "#fffac8",
    "#800000", "#aaffc3", "#808000", "#ffd8b1", "#000075", "#a9a9a9", "#000000")
names(cl.colors) = as.character(0:20)
```

Load ST data

```{r}
st.data = readRDS(file = "seurat_object_stereoscope_neut.rds")
table(st.data$CelltypeCluster)
st.data.ori = readRDS(file = "seurat_object_stereoscope.rds")

DefaultAssay(st.data) <- "Spatial"
st.data@active.ident <- st.data$seurat_clusters

p1 = DimPlot(st.data, label = T, cols = cl.colors) + NoAxes() + ggtitle("Integrated clusters")
p3 = DimPlot(st.data, group.by = "Sample_name") + NoAxes()
grid.arrange(p1, p3, ncol = 2)

p2 = SpatialDimPlot(st.data, stroke = 0, cols = cl.colors, combine = F)
grid.arrange(grobs = p2, ncol = 4)
```

```{r}
total.names = colnames(st.data@meta.data)[grep("Total_", colnames(st.data@meta.data))]

p = SpatialFeaturePlot(st.data, total.names, combine = F)

for (i in 1:16) {
    pl = p[i + c(0, 16, 32, 48)]
    grid.arrange(grobs = pl, ncol = 4)
}
```

```{r}
plot.gene.umap = function(sdata, genes, reduction = "umap", assay = "Spatial", ncol = 5,
    nrow = 6, nPlot = NULL) {
    cc = scale_color_gradientn(colors = c("grey", "yellow", "red", "black"))
    small.leg <- theme(legend.text = element_text(size = 6), legend.key.width = unit(0.1,
        "cm"))
    sdata@active.assay = assay
    pl = list()
    for (i in 1:length(genes)) {
        pl[[i]] = FeaturePlot(sdata, features = genes[i], slot = "data", pt.size = 0.01,
            order = T, reduction = reduction) + NoAxes() + cc + small.leg + ggtitle(genes[i]) +
            theme(plot.title = element_text(size = 10))
    }
    if (is.null(nPlot)) {
        nPlot = length(genes)
    }
    if (nPlot > ncol * nrow) {
        print("Cannot fit all figures into a single plot")
        nPlot = ncol * nrow
    }
    nBin = ceiling(length(pl)/nPlot)
    for (i in 1:nBin) {
        x = (i * nPlot + 1 - nPlot):min(length(pl), i * nPlot)
        grid.arrange(grobs = pl[x], ncol = ncol, nrow = nrow)
    }
}

celltypes <- rownames(st.data@assays$Stereoscope@counts)
plot.gene.umap(st.data, celltypes, assay = "Stereoscope")
```

```{r}
st.data@active.assay = "Stereoscope"
for (g in celltypes) {
    p = SpatialFeaturePlot(st.data, features = g, images = samples, alpha = c(0.2,
        1), combine = F)
    grid.arrange(grobs = p, ncol = 4, top = g)
}
```

### Session info

```{r}
sessionInfo()
```
